### ISSUE TITLE
IgnoreInvalidPunycode set to false breaks my domain

### ISSUE THREAD

**Issue by socram8888** [servo/rust-url#1001]
- [x] Note that this crate implements the [URL Standard](https://url.spec.whatwg.org/) not RFC 1738 or RFC 3986

**Describe the bug**
The UTS46 implementation, due to its hardcoding of `IgnoreInvalidPunycode` to false, is unable to parse the domain `xn--i29h.kz`, which is valid according to .kz restrictions and is currently registered, making it inaccesible on Firefox (https://bugzilla.mozilla.org/show_bug.cgi?id=1933170)

WHATWG does not cover what the correct value for said flag should be. Chrome does set it to true, making the domain accesible via Punycode (though not directly as Unicode, which is the behavior I'd expect).

**Comment by valenting** [comment]
Depends on https://github.com/whatwg/url/issues/821 being resolved
