### ISSUE TITLE
Would it be worthwhile to add a `TryFrom<String>` implementation?

### ISSUE THREAD

**Issue by Scripter17** [servo/rust-url#1010]
In a project I'm working on, parsing URLs is a not-insignificant amount of the runtime, and a sizable portion of that seems to just be `String::push` from `Url::from_str`. In extreme cases this seems to be up to 10% of the program's runtime, but even on much more reasonable cases it reaches 5%.

Given I already always have a `String` that I never want outside of a `Url`, it feels like you could skip the copying entirely.

**Comment by Manishearth** [comment]
I don't think the optimization you suggest is possible: the parser does not merely append the string it receives to a buffer, it does a bunch of changes to it too.

It may be possible to reduce the number of separate push calls being made, however.

**Comment by Scripter17** [comment]
How common are those modifications? 99% of the URLs I encounter don't seem to me like they require any modification to work. Or is it internal stuff like that SIMD JSON parser crate making a mess of byte slices as it deserializes

I think it's fine for `TryFrom<String>` to just be a best effort and fall back to `FromStr` any time it needs to do that
