### ISSUE TITLE
Windows build regularly gets broken

### ISSUE THREAD

**Issue by SimonSapin** [servo/rust-url#102]
Since [the `std::path` reform](https://github.com/rust-lang/rfcs/pull/474), that module switched to having a single `Path` type with conditionally-compiled platform-specific behavior instead of separate `std::path::unix::Path` and `std::path::windows::Path` types and only a platform-specific re-export as `std::path::Path`.

rust-url also has some platform specific behavior for converting between `Path` and `file://` URLs. Previously, we could implement traits for both `Path` types and have that code exist and all platforms. Now that it’s a single type, we have to use `#[cfg(…)]` to do conditional compilation too.

This is a long way to say that we now have Windows-specific code that is not compiled on Unix. Since I don’t use Windows and Windows is not available on Travis-CI, this code often gets broken without me noticing: #89, #96, #101.

**Comment by jaxx** [comment]
@SimonSapin, I think that build actually broke with #99, when `iter()` was removed :)

**Comment by SimonSapin** [comment]
@jaxx yes, probably. But the deeper problem is that we have code that I never build or test, so it inevitably breaks.

**Comment by SimonSapin** [comment]
93bc3d1f44babcb3040ba50eb6b9541bc7655edb should avoid most of these issues.

**Comment by SimonSapin** [comment]
http://www.appveyor.com/ could help as well. Anyone want to try it? CC @jaxx @fuchsnj @alexcrichton

**Comment by SimonSapin** [comment]
We’re now testing on Windows with Appveyor: #105
