### ISSUE TITLE
use of undeclared trait name `IntoIterator` in form_urlencoded.rs

### ISSUE THREAD

**Issue by gfmio** [servo/rust-url#103]
On Mac OS X 10.10.3 with Rust rustc 1.0.0-beta.2, compilation of the package fails, because the IntoIterator has not been declared with use.

Can be fixed by including use `std::iter::IntoIterator;` in form_urlencoded.rs.

**Comment by SimonSapin** [comment]
I believe `IntoIterator` was added to the prelude recently. Does upgrading to 1.0.0-beta.4 fix this?

**Comment by gfmio** [comment]
Ah, yes, thank you. Sorry, I should have checked for Rust updates first.

**Comment by SimonSapin** [comment]
No worries! Closing based on your “it works now”.
