### ISSUE TITLE
Implement Nameprep for IDNA

### ISSUE THREAD

**Issue by KiChjang** [servo/rust-url#112]
* Relevant spec: https://url.spec.whatwg.org/#idna, http://www.unicode.org/reports/tr46/#Processing
* Code: `src/host.rs`, and a new file, possibly `src/nameprep.rs`

**Comment by KiChjang** [comment]
I'm actually a little confused... there are 3 standards we are looking at here: IDNA2003, UTS46 and IDNA2008. Which should we be using?

**Comment by SimonSapin** [comment]
Yeah, IDNA is a mess, with versions incompatible with each other…

We want to implement https://url.spec.whatwg.org/#idna , which refers to UTS 46.
