### ISSUE TITLE
Optimize Url::hash

### ISSUE THREAD

**Issue by alexcrichton** [servo/rust-url#113]
The [current implementation of the `Hash` trait](https://github.com/servo/rust-url/blob/911c805991a4e77056e72e3c849655e174d70e64/src/lib.rs#L237-L241) calls `serialize`, which allocates a `String` and then hashes the contents of that. Cargo's use case, at least, involves hashing quite a few URLs, and I've often seen this function very high up in the profiles of Cargo.

**Comment by SimonSapin** [comment]
It should be doable to write an adapter from `Write` (to be used with the formatting mechanism instead of `String`) to `Hasher` (or whatever it’s called). Or perhaps it should just be `#[derive(Hash)]`, I don’t know.

**Comment by alexcrichton** [comment]
Either way would probably work pretty well, I also don't mind profiling before/after before a change is landed just to make sure it has the impact I think it'll have!

**Comment by SimonSapin** [comment]
Published 0.2.35 with `#[derive(Hash)]`, let me know if it helps.
