### ISSUE TITLE
Large ports cannot be parsed

### ISSUE THREAD

**Issue by nox** [servo/rust-url#115]
https://github.com/w3c/web-platform-tests/blob/11f3aee19205a2ae97efa1cbeb211a2395192ea8/url/urltestdata.txt#L19

**Comment by SimonSapin** [comment]
This is a wilful violation of the spec. Spec issue: https://www.w3.org/Bugs/Public/show_bug.cgi?id=26446

**Comment by SimonSapin** [comment]
@valenting Do you or other people in the Necko team have an opinion on this? That is, as far as the parser is concerned, should the port number be a string of decimal digits (with no length limit), a 16-bit integer (matching TCP and UDP), or something else? I believe it’s currently a 32-bit integer in Gecko.

**Comment by valenting** [comment]
I think the reason it's an int32_t in Gecko is that for a URL with a default port number, we represent it as -1.
I have been considering rejecting invalid port numbers for a while now.
rust-url has the benefit of being able to represent it as None, so as far as I'm concerned, it would be best to represent it as a u16.

**Comment by SimonSapin** [comment]
Would `Maybe<uint16_t>` (from `mfbt/Maybe.h`) work to represent `Option<u16>`?

**Comment by valenting** [comment]
I think so, but at this point it's too late to change the APIs.
We can however restrict the parsing of port numbers to the uint16_t range. I expect the spec will eventually be changed to express that constraint.

**Comment by SimonSapin** [comment]
The spec now agrees with rust-url on this.

“Make port either null or a 16-bit integer.” https://github.com/whatwg/url/commit/c3a454c073d6bf9f24d8ee2b5c3e6e006b943777
