### ISSUE TITLE
Invalid IPv4 addresses are not rejected

### ISSUE THREAD

**Issue by nox** [servo/rust-url#116]
https://github.com/w3c/web-platform-tests/blob/11f3aee19205a2ae97efa1cbeb211a2395192ea8/url/urltestdata.txt#L325

**Comment by SimonSapin** [comment]
I believe this test does not match the current spec, but in this case I think the spec should be changed. Spec issue: https://www.w3.org/Bugs/Public/show_bug.cgi?id=26431

**Comment by frewsxcv** [comment]
Spec has been resolved

**Comment by nox** [comment]
This was closed, but we never added `http://192.168.0.257` to the tests.
