### ISSUE TITLE
Escaped chars in username / password are not unescaped

### ISSUE THREAD

**Issue by divarvel** [servo/rust-url#120]
The following lines added to `src/urltestdata.txt` make the tests fail

    http://:passw%2ford@www.example.com  s:http pass:pass/word h:www.example.com p:/
    http://us%40er:password@www.example.com  s:http u:us@er pass:password h:www.example.com p:/

As per the spec: 

     The user name (and password), if present, are followed by a
     commercial at-sign "@". Within the user and password field, any ":",
     "@", or "/" must be encoded.

There seems to be unescaping happening there, though.

<https://github.com/servo/rust-url/blob/master/src/parser.rs#L348>

**Comment by SimonSapin** [comment]
Which spec are you quoting? This library implements https://url.spec.whatwg.org/.

The expected value of fields in `urltestdata.txt` correspond to [the `URLUtils` interface](https://url.spec.whatwg.org/#api) implemented by browsers, where data is percent-encoded. For example, this shows `a%40b`:

```html
data:text/html,<a href="http://a@b@example.net"></a><script>document.write(document.getElementsByTagName('a')[0].username)</script>
```

**Comment by divarvel** [comment]
I was referring to RFC1738 which seem outdated indeed.
I've had a closer look at the whatwg url spec and I'm not sure I understand why username and password should be percent encoded when parsed (no decoding is required when serializing an URL), but that's not something to discuss here :-)

Sorry for the bother.

**Comment by SimonSapin** [comment]
My understanding is that this is the behavior you want on the client side, so that the fields of a parsed URL correspond to what’s gonna be sent on the network when making a request for that URL. Server-side code might make different choices.

**Comment by divarvel** [comment]
Oh, I understand it now, it does not parse a serialized url, it parses an url typed by the user. So parsing . serialization should not be identity. Thanks for the explanation.

**Comment by SimonSapin** [comment]
It parses for example what’s found in the `href` attribute of an `a` element, which can be anything. `serialize(parse(X))` is not necessarily `X` for any `X`, but `parse(serialize(parse(X)))` should be the same as `parse(X)` I think.
