### ISSUE TITLE
Misleading Description

### ISSUE THREAD

**Issue by bfrog** [servo/rust-url#121]
While this library does indeed parse urls, it also helps encode them, the description on crates.io doesn't suggest it though which lead me to skip over it when first searching. A package description including url encoding would help.

**Comment by SimonSapin** [comment]
What kind of encoding do you mean? [Percent-encoding](https://url.spec.whatwg.org/#percent-encoded-bytes)? What should the description include?

**Comment by bfrog** [comment]
Maybe something like "URL parsing and encoding" or the "URL library for Rust" like described in the github Readme.

**Comment by SimonSapin** [comment]
I’m still not sure what "encoding" means to you in this context. Is it that the fields in the `Url` struct are percent-encoded? Is it the [`percent_encoding`](https://servo.github.io/rust-url/url/percent_encoding/index.html) module that you can use on any string, independently of URLs?

**Comment by bfrog** [comment]
https://github.com/servo/rust-url/blob/master/src/lib.rs#L55

There's quite a few serialize_* methods besides that one that work on a Url struct.

https://github.com/servo/rust-url/blob/master/src/form_urlencoded.rs#L93

Serialize url query strings (form encoding).

I actually don't fully understand what you mean by percent encoding. But my impression of this library is that it would be the near equivalent of 

http://golang.org/pkg/net/url/

or 

http://docs.oracle.com/javase/7/docs/api/java/net/URL.html

Which let you both parse and encode URLs , not just the query string parts but the entire URL. And certainly not just parse them.

**Comment by SimonSapin** [comment]
Percent-encoding is replacing non-ASCII bytes or bytes that would otherwise have a special meaning with a `%` percent sign followed by two hexadecimal digits representing the value of that byte: https://url.spec.whatwg.org/#percent-encoded-bytes

Sorry, I still don’t understand what "encode an URL" means to you, and how it’s different from parsing. Could you expand a bit more, without reusing the same words?

**Comment by bfrog** [comment]
This library not only parses strings (containing urls) in to a data structure but also to serialize (or encode) that data structure back in to a string (representing a url) including the query parameters, probably using the url encoding your talking about (percent encoding?). I'm not sure why "encoding" became such a problematic term communicating that.

I think saying it is a URL parser library makes it harder to find as a general purpose URL manipulation and Rust struct representation library, which it appears to be. I wasn't looking for a URL parsing library, I was looking for a library to create a URL from a bunch of parts of a URL like the golang and java libraries let me do. Those libraries don't call themselves URL parsers, just URL libraries.

**Comment by SimonSapin** [comment]
Ah! I finally got it, you call encode what I call serialize. Sorry for the confusion :)

How does this look? https://github.com/servo/rust-url/pull/122

**Comment by bfrog** [comment]
Perfect!
