### ISSUE TITLE
`port: None` should be equal to `port: default_port`

### ISSUE THREAD

**Issue by untitaker** [servo/rust-url#132]
The iron framework constructs an URL with `RelativeSchemeData { port: 42, default_port: 42, ... }` (see iron/iron#400). The url crate should treat this as equal to `RelativeSchemeData { port: None, default_port: 42 }`.

At least this behavior would make sense for HTTP URLs.

**Comment by SimonSapin** [comment]
Sorry, it’s been a while and I don’t have all the details of rust-url on the top of my head right now. What behavior in particular would you like to change? (What methods?)

**Comment by untitaker** [comment]
Eq trait impl

On 27 October 2015 21:15:54 CET, Simon Sapin <notifications@github.com> wrote:
>Sorry, it’s been a while and I don’t have all the details of rust-url
>on the top of my head right now. What behavior in particular would you
>like to change? (What methods?)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/servo/rust-url/issues/132#issuecomment-151629774

-- 
Sent from my phone. Please excuse my brevity.
