### ISSUE TITLE
Consider ignoring UTS46 validity criteria V2

### ISSUE THREAD

**Issue by valenting** [servo/rust-url#160]
```
Each of the following criteria must be satisfied for a label:
2. The label must not contain a U+002D HYPHEN-MINUS character in both the third and fourth positions. 
```

However, it seems that other UAs don't enforce this, and it matches domains commonly used on youtube. ex: r6---sn-5hne6nee.googlevideo.com

**Comment by SimonSapin** [comment]
In that case, UTS-46 should probably be changed to match reality. It says:

> Please submit corrigenda and other comments with the online reporting form [[Feedback](http://www.unicode.org/reporting.html)].

so you should do that. But since Unicode doesn’t have a public bug tracker, it’d be good to also track it in https://github.com/whatwg/url/issues/53.

**Comment by valenting** [comment]
Just to note, I raised the issue using the reporting form, and they took note of the offending URLs such as http://r6---sn-5hne6nee.googlevideo.com
```
The rule is only included because the IETF wanted to reserve labels of the form XX--... for future use, in case they wanted another signature like "xn--"
```
They will probably address this in the June release of the next version.

**Comment by Manishearth** [comment]
I think we should make accepting this behavior an option in `ParseOptions`.

@canaltinova want to try working on this? see https://github.com/servo/rust-url/issues/207 for more context

**Comment by canaltinova** [comment]
Sure, I can give it a try :)

**Comment by SimonSapin** [comment]
I'm convinced it's worth an option. If nobody follows a spec on some detail, it's a spec bug and we should just align with other implementation.

**Comment by thomcc** [comment]
Did this ever get an option? Currently hitting this in https://github.com/mozilla-mobile/fenix/issues/2994

**Comment by SimonSapin** [comment]
I don’t remember any of the details, but this issue is marked as closed by https://github.com/servo/rust-url/pull/240.
