### ISSUE TITLE
Track spec changes somehow

### ISSUE THREAD

**Issue by SimonSapin** [servo/rust-url#163]
1. Pick a commit of http://url.spec.whatwg.org/
2. Go through all of it, fix rust-url where we differ or file issues. This will be slow and boring and needs to be done very carefully.
3. Keep track of that which commit of the spec we’re up-to-date with, modulo filed issues
4. Regularly, go through new commits on the spec repository and update code or file new issues for spec changes

**Comment by gerv** [comment]
2. needs to involve writing tests, presumably.

**Comment by SimonSapin** [comment]
We run a copy of the tests at https://github.com/w3c/web-platform-tests/tree/master/url. If some start failing after we update them, that’s one way to find out that we probably need some code change. But ideally we’d still go through the spec’s text in case some aspect is not covered by the test suite. In this case, yes, we should write new tests and contribute them upstream.

**Comment by SimonSapin** [comment]
(Well, not all of https://github.com/w3c/web-platform-tests/tree/master/url since we don’t have a DOM in this repo’s unit tests, but the subset based on JSON data.)

**Comment by djc** [comment]
I've updated the JSON to URL Standard's current master in #623.
