### ISSUE TITLE
Having Url::parse borrow its input?

### ISSUE THREAD

**Issue by SimonSapin** [servo/rust-url#180]
Discussion in https://github.com/servo/rust-url/pull/176 is long and covers many topics. I’m splitting off here the one about avoiding `String` allocations. Here is the only design that I think is realistic: have a type like `Cow<str>` that borrows when possible, and falls back to an owned string when necessary:

```rust
enum PrefixCowStr<'a> {
    Borrowed { s: &'a str, len: usize },
    Owned(String),
}

impl<'a> ::std::ops::Deref for PrefixCowStr<'a> {
    type Target = str;
    fn deref(&self) -> &str {
        match *self {
            PrefixCowStr::Borrowed { s, len } => &s[..len],
            PrefixCowStr::Owned(ref s) => &**s,
        }
    }
}

impl<'a> PrefixCowStr<'a> {
    fn new(s: &'a str) -> Self {
        PrefixCowStr::Borrowed { s: s, len: 0 }
    }

    fn push_str(&mut self, new: &str) {
        match *self {
            PrefixCowStr::Borrowed { s, len } => {
                if s[len..].starts_with(new) {
                    *self = PrefixCowStr::Borrowed { s: s, len: len + new.len() }
                } else {
                    *self = PrefixCowStr::Owned(s.to_owned() + new)
                }
            }
            PrefixCowStr::Owned(ref mut s) => s.push_str(new),
        }
    }

    fn push(&mut self, new: char) {
        match *self {
            PrefixCowStr::Borrowed { s, len } => {
                if s[len..].starts_with(new) {
                    *self = PrefixCowStr::Borrowed { s: s, len: len + new.len_utf8() }
                } else {
                    let mut s = s.to_owned();
                    s.push(new);
                    *self = PrefixCowStr::Owned(s)
                }
            }
            PrefixCowStr::Owned(ref mut s) => s.push(new),
        }
    }

    fn truncate(&mut self, new_len: usize) {
        match *self {
            PrefixCowStr::Borrowed { s, ref mut len } => {
                // Panic if new_len > current length or if new_len does not lie on a char boundary.
                &s[..new_len];
                *len = new_len
            }
            PrefixCowStr::Owned(ref mut s) => s.truncate(new_len),
        }
    }

    fn into_string(self) -> String {
        match self {
            PrefixCowStr::Borrowed { s, len } => s[..len].to_owned(),
            PrefixCowStr::Owned(s) => s,
        }
    }

    fn into_static(self) -> PrefixCowStr<'static> {
        PrefixCowStr::Owned(self.into_string())
    }
}
```

This new type is an abstraction that checks `starts_with` internally so that we don’t have to do it all over the place in `src/parser.rs`. The parsing algorithm and the `Url` struct could use this instead of `String`. `Url` could itself have an `into_static` method.

This would only be a benefit when we end up staying in the `Borrowed` variants. But there are lots of cases where that’s not the case: IDNA/punycode, percent-encoding, relative URLs, …

A downside is that, of course, `Url` would gain a lifetime parameter. Borrowing the input means you can not outlive it, which can be restrictive for example for moving an URL into a non-scoped thread. (`std::thread::spawn` has a `'static` bound on its closure.) `Url::into_static` can be used in these cases, but all these efforts we made to avoid allocating end up for nothing in that case.

Another downside is the extra cost in all these `starts_with` calls and branches. Are these accumulated costs really worth avoiding allocation in **some** (few?) cases? jemalloc can be a to faster than intuition says.

CC @asajeffrey @nox

**Comment by nox** [comment]
The earlier discussion made me realise it doesn't look like a complexity we really want.

**Comment by SimonSapin** [comment]
To be clear, I wanted to write up this idea but I think it’s not a great trade-off and we should stick with `String`.

**Comment by kamalmarhubi** [comment]
@SimonSapin thanks for writing this up! I think I agree that this should not be the default in `Url`. I don't have enough intuition in this area to make any meaningful comments. I *certainly* don't have an example server lying around to test with. :/

**Comment by kamalmarhubi** [comment]
One thing I don't know: do major browsers {percent-encode, puny-encode, path normalize} before sending the request? I'm wondering how often a URL in a request will not result in a backing store that is 1:1 with the input. I'm again reminded of Kelly Sommers' tweet

> Adding the mark and sweep buffer manager to Haywire increased benchmarks by 300,000 requests/sec cuz now URL's are zero-copy & less allocs.

―https://twitter.com/kellabyte/status/705833684327403520

which makes it seem worth avoiding copies for server software. On the other hand, perhaps those really high performance servers should have their own URL type and not make everyone pay in usability for them to gain a few percent requests per second.

**Comment by SimonSapin** [comment]
Yes, https://url.spec.whatwg.org/ is written with browsers interoperability in mind.

But even when the input is already-encoded and normalized, relative URLs are very common. For example, the HTML form I’m typing this comment in has markup like `<form action="/servo/rust-url/issue_comments">`, with a base URL of `https://github.com/servo/rust-url/issues/180`. The parsed URL for that is `https://github.com/servo/rust-url/issue_comments`. It’s not a substring of either the input or the base.

I’m all for avoiding copies and allocations when possible. I spent a lot of time in #176 making more things use `&str` or `Cow<str>` instead of `String`. But in the specific case of `Url::parse` I really don’t think it’s worth it.
