### ISSUE TITLE
Consider implementing Url::has_network_scheme

### ISSUE THREAD

**Issue by Ms2ger** [servo/rust-url#182]
Per https://url.spec.whatwg.org/#network-scheme

**Comment by SimonSapin** [comment]
In the meantime, with https://crates.io/crates/matches,

0.5:

```rust
matches!(&*url.scheme, "ftp" | "http" | "https")
```

1.0:

```rust
matches!(url.scheme(), "ftp" | "http" | "https")
```

**Comment by SimonSapin** [comment]
Ok, read https://github.com/servo/servo/pull/10304#issuecomment-203833791. To clarify my stance: I don’t mind adding this if you or @nox feels strongly about it, but I think it may not be worth adding API surface given how simple it is to implement and how infrequently it is needed.

**Comment by nox** [comment]
I like to have small functions for small concepts that are defined by the spec.

After all:

> based on the URL Standard.

**Comment by SimonSapin** [comment]
That quote means that things that are in rust-url are implemented per that spec, not necessarily that all things in that spec are present in the crate :)

**Comment by nox** [comment]
Details, details… :D

**Comment by Ms2ger** [comment]
I don't feel strongly either, though it'd be nice not to have to find some place to put the function instead.

**Comment by SimonSapin** [comment]
Closing, I’m skeptical that anything other than of Servo would use this and it’s easy to define in Servo.
