### ISSUE TITLE
canonicalized paths on windows 

### ISSUE THREAD

**Issue by yoava333** [servo/rust-url#184]
if you use PathBuf canonicalize() method you will get a path in the form of "\\?\C:\..."
If you try to pass this to Url::from_file_path you get an error.
This causes https://github.com/servo/servo/issues/10548

**Comment by SimonSapin** [comment]
Fixed in #185.

Note: if you use "fixes #184" or "closes #184" in a commit message or PR description, github will automatically close the referenced issue when the PR is merged: https://github.com/blog/1386-closing-issues-via-commit-messages
