### ISSUE TITLE
Add domain to the origin tuple

### ISSUE THREAD

**Issue by KiChjang** [servo/rust-url#193]
The [specification](https://url.spec.whatwg.org/#origin) has updated and now it is a 4-tuple, consisting of the scheme, host, port and domain. Is this a breaking change?

**Comment by Ms2ger** [comment]
This exists only to support the `document.domain` setter, which we don't intend to implement particularly soon. Even then, `URL::origin()` will never return an origin with the domain set to anything else than `None`, so we can implement it in Servo itself.

**Comment by KiChjang** [comment]
Also, there exists a `Url::domain` method, which can easily be used to check whether a URL contains a domain. Closing.
