### ISSUE TITLE
Latest cargo can't parse Cargo.toml?

### ISSUE THREAD

**Issue by petevine** [servo/rust-url#195]
I'm getting a strange error from `url 0.5.9`:

```shell
error: unable to get packages from source

Caused by:
  failed to parse manifest at `.cargo/registry/src/github.com-48ad6e4054423464/url-0.5.9/Cargo.toml`

Caused by:
  could not parse input as TOML
.cargo/registry/src/github.com-48ad6e4054423464/url-0.5.9/Cargo.toml:14:3 expected a newline after table definition
````

You probably know what's happening - cargo bug, breaking change?

**Comment by metajack** [comment]
@alexcrichton Ideas?

**Comment by alexcrichton** [comment]
Yes this was a bug fix to TOML parsing in https://github.com/alexcrichton/toml-rs/pull/94, but Cargo has not yet been upgraded to have that bugfix. That is being done as part of https://github.com/rust-lang/cargo/pull/2680 in a way that will not emit this error.

I don't really know why you would be seeing this error unless you custom compiled Cargo against a newer version of TOML manually, none of our releases should have this.

**Comment by metajack** [comment]
We're using 2016-05-12 nightly.

**Comment by petevine** [comment]
I don't recall modifying any dependencies and the latest git source doesn't produce a cargo like that.
Oh well.

**Comment by SimonSapin** [comment]
If this keeps being a problem I can publish url 0.5.10 with more newlines in `Cargo.toml`.

**Comment by SimonSapin** [comment]
(1.x versions do that already.)

**Comment by xpe** [comment]
@SimonSapin yes, it would be useful to push a new version in the 0.5.x series with https://github.com/servo/rust-url/commit/e362e1382784ccf455533183fde0d12666aa3fac

```
warning: TOML file found which contains invalid syntax and will soon not parse
at `/Users/xpe/.cargo/registry/src/github.com-1ecc6299db9ec823/url-0.5.9/Cargo.toml`.

The TOML spec requires newlines after table definitions (e.g. `[a] b = 1` is
invalid), but this file has a table header which does not have a newline after
it. A newline needs to be added and this warning will soon become a hard error
in the future.
```
