### ISSUE TITLE
Support of URL object

### ISSUE THREAD

**Issue by izgzhen** [servo/rust-url#196]
Spec: https://url.spec.whatwg.org/#concept-url-object

Primarily used by [Blob URL](https://w3c.github.io/FileAPI/#DefinitionOfScheme)

Although spec goes in that way, I doubt if this might be easy to follow. First, the Blob object is something outside this crate and defined by WebIDL (or implementation, like servo). Second, it can be very confusing to attach a payload field to an URL I think.

**Comment by SimonSapin** [comment]
I’m not sure what it would mean to support blobs in this create. Maybe this belongs in a wrapper type like Servo’s http://doc.servo.org/script/dom/url/struct.URL.html ?

**Comment by izgzhen** [comment]
Not sure. Looks like the DOM interface `URL` is for some scripting usage, like constructing a URL or create the Blob URL from Blob. But adding an object to this crate is really awkward I think.

**Comment by SimonSapin** [comment]
I’m tempted to close this issue with no change, and leave Servo to figure out where in their own types the blob object should go. What do you think?

**Comment by izgzhen** [comment]
Ok, thanks
