### ISSUE TITLE
Panic 'index out of bounds: the len is 7 but the index is 7'

### ISSUE THREAD

**Issue by alexcrichton** [servo/rust-url#197]
This program:

```rust
extern crate url;

use url::Url;

fn main() {
    let mut url = Url::from_file_path("/").unwrap();
    url.path_segments_mut().unwrap().pop_if_empty();
}
```

will panic with:

```
thread '<main>' panicked at 'index out of bounds: the len is 7 but the index is 7', src/lib.rs:1095
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Oddly enough the "equivalent" program of `Url::parse("file://")` works just fine!

**Comment by SimonSapin** [comment]
Thanks for the report! The problem is that `from_file_path("/")` would return an URL whose serialization is `file://` with no path, which some other code assumes never happens. #198 fixes this.

**Comment by alexcrichton** [comment]
Oh wow, thanks for the quick fix!
