### ISSUE TITLE
requirements for parsing HTTP headers containing URLs

### ISSUE THREAD

**Issue by db48x** [servo/rust-url#2]
I'm working on Teepee https://github.com/teepee/teepee/, and we want to use rust-url to implement parsers for some HTTP headers. There are four headers that may contain URLs, or parts of them.

The Location header must be an absolute URL, and so must fail when the value is relative.

The Content-Location and Referer headers may be relative, but because all parsers for HTTP headers must have the same function signature, we would prefer not to have to specify a base URL. The algorithm specified by http://url.spec.whatwg.org/ seems to work this way. We would prefer to have an enum that tells us whether a URL is absolute or relative. Something like this, perhaps:

```
enum TypedUrl {
  Absolute(Url),
  Relative(Url)
}
```

Completely different types would also work.

Finally, the Host header has just a hostname or IP address. I'm currently using your Host type for that.

The code is available at https://github.com/db48x/teepee/blob/parse-some-headers/src/httpcommon/headers/url_based.rs.

**Comment by galsondor** [comment]
I think there is some misunderstanding about "absolute" and "relative" with respect to URLs.  These two terms do not refer to the URL path, rather to the existence (or non existence) of a scheme (e.g., "http").  Although parsing the URL forms mentioned above is possible without a base URL, reference resolution (RFC 3986 sec 5) *requires* a base URL if the path itself is not absolute.  For most headers, the base is URL used to retrieve the headers (although the Link header allows the base to be overridden using "anchor"--see RFC 5988). This library currently combines parsing and resolution.  Perhaps separation of parsing and reference resolution should be considered.

**Comment by SimonSapin** [comment]
Closing in favor of https://docs.rs/http/0.1.13/http/uri/struct.Uri.html, which is designed specifically for representing the `request-target` on an HTTP request.
