### ISSUE TITLE
Please make a 0.5.10 release with updated Cargo.toml

### ISSUE THREAD

**Issue by xpe** [servo/rust-url#204]
From this issue: https://github.com/servo/rust-url/issues/195 (currently closed)

@SimonSapin yes, it would be useful to push a new version in the 0.5.x series with https://github.com/servo/rust-url/commit/e362e1382784ccf455533183fde0d12666aa3fac

```
warning: TOML file found which contains invalid syntax and will soon not parse
at `/Users/xpe/.cargo/registry/src/github.com-1ecc6299db9ec823/url-0.5.9/Cargo.toml`.

The TOML spec requires newlines after table definitions (e.g. `[a] b = 1` is
invalid), but this file has a table header which does not have a newline after
it. A newline needs to be added and this warning will soon become a hard error
in the future.
```

**Comment by xpe** [comment]
I've made [only whitespace changes to url 0.5.9][1] to [my local crate configuration in `.cargo/config`][2], but now I'm getting this error:

[1]: https://github.com/xpe/rust-url/commit/c7f36a6677f72cf8532638e87323805efec99cae

[2]: http://doc.crates.io/config.html

```
/Users/xpe/.cargo/registry/src/github.com-1ecc6299db9ec823/cookie-0.2.5/src/lib.rs:34:67: 34:78 error: no method named `decode_utf8` found for type `std::vec::Vec<u8>` in the current scope
/Users/xpe/.cargo/registry/src/github.com-1ecc6299db9ec823/cookie-0.2.5/src/lib.rs:34     match url::percent_encoding::percent_decode(input.as_bytes()).decode_utf8() {
```

I have not figured out why only changing whitespace triggered this error.

**Comment by SpaceManiac** [comment]
Using the `.cargo/config` method to override the `url` crate will not work if any other version of `url` is used anywhere in your dependency tree (for example, `cookie 0.2.5` depending on `url 1.2.5` but being substituted the incompatible `url 0.5.9`). Instead, you can use Cargo's `[replace]` in your `Cargo.toml`:

```
[replace]
"url:0.5.9" = { git = "<your own clone>", branch = "<branch with whitespace fix>" }
```

This is just a workaround and this `[replace]` section pointing to a git repo containing the patch needs to be included in *every downstream crate, recursively*, at which point why has the `url` crate upstream not just patched the problem?

Crates which still depend, even transitively, on `url 0.5.9` will eventually start breaking for no good reason. There ought to be a `url 0.5.10` which fixes the `Cargo.toml`.

**Comment by Hoverbear** [comment]
I'm looking into this. Expect a new version soon.

**Comment by Hoverbear** [comment]
Please enjoy  ef427c8  which is published as `0.5.10` [here](https://crates.io/crates/url).

**Comment by SimonSapin** [comment]
Uh, I meant to do this two months ago but forgot. Sorry. Thanks for taking care of it @Hoverbear !

**Comment by Hoverbear** [comment]
Glad I didn't step on any toes. :)
