### ISSUE TITLE
IDNAError on valid URL

### ISSUE THREAD

**Issue by Manishearth** [servo/rust-url#207]
```
let z = Url::parse("https://r2---sn-huoa-cvhl.googlevideo.com/crossdomain.xml");
```
is an `Err(IdnaError)`. The punycode URL works in Firefox.

The error comes from the idna subcrate, where `domain_to_ascii("r2---sn-huoa-cvhl.googlevideo.com/crossdomain.xml")` fails.

cc @SimonSapin

**Comment by jezell** [comment]
http://www.unicode.org/reports/tr46/#Validity_Criteria

The label must not contain a U+002D HYPHEN-MINUS character in both the third and fourth positions.

The first 5 criteria are from [IDNA2008]. Criterion #2 in particular is meant to allow for future label extensions beyond just xn--, such as for future versions of IDNA. Some implementations appear to consider such extentions unlikely, and allow labels such as "r3---sn-apo3qvuoxuxbt-j5pe".

So the spec says it's invalid, sort of, but explicitly calls out that some implementations ignore this rule. Maybe should be a flag to relax this validation during parse?

**Comment by Manishearth** [comment]
> So the spec says it's invalid, sort of, but explicitly calls out that some implementations ignore this rule. 

Welcome to my world 😄

**Comment by Manishearth** [comment]
Out of curiosity, how did you find this bug? Pretty surprised that it got diagnosed and fixed by someone not previously affiliated with the project within an hour. Thanks for that 😄.

**Comment by Manishearth** [comment]
Oh, because I posted the issue on HN. Makes sense, always nice to have new contributors!

**Comment by annevk** [comment]
Is this a duplicate of #160?

**Comment by Manishearth** [comment]
yep.
