### ISSUE TITLE
port not parsed

### ISSUE THREAD

**Issue by puhrez** [servo/rust-url#214]
```
// Cargo.toml
 [package]
 name = "test-url"
 version = "0.1.0"

 [dependencies]
 url = "1.1.1"

```

```
// main.rs
extern crate url;

use url::Url;

fn main() {
    let url = Url::parse("http://github.com:80").unwrap();
    println!("host: {:?}, port: {:?}", url.host_str(), url.port());
}
```

output:

```
 host: Some("github.com"), port: None 
```

**Comment by puhrez** [comment]
perusing the code, I find no port parsing code

**Comment by jdm** [comment]
It exists in https://github.com/servo/rust-url/blob/28d691c870223b3240ed8d284752ea7847774430/src/parser.rs#L721 . I believe if the default port for the scheme is provided then None is used instead?

**Comment by jdm** [comment]
Yes, that's what https://github.com/servo/rust-url/blob/28d691c870223b3240ed8d284752ea7847774430/src/parser.rs#L855 does.

**Comment by puhrez** [comment]
fair my rgreping skills need some work; is this good behaviour?

For example, as a user, I'd expect `.port()` on any `http` url to return `Some(80)` not `None` even thought `80`is the default port. It's rather implicit.

**Comment by emilio** [comment]
I think you're looking for `port_or_known_default` :)

**Comment by SimonSapin** [comment]
Closing. This behavior is as specified in https://url.spec.whatwg.org/#port-state

> Set *url*’s port to null, if *port* is *ur*l’s scheme’s default port, and to *port* otherwise.

As Emilio said, the `port_or_known_default` method returns `Some(80)` in this case.
