### ISSUE TITLE
Query parameter serialization for arbitrary bytes (not just UTF-8)

### ISSUE THREAD

**Issue by michael-younkin** [servo/rust-url#219]
At the moment, `url::form_urlencoded::Serializer` only allows you to append pairs using `str`s, which must contain valid UTF-8 data. As far as I can tell, this means it isn't possible to encode arbitrary binary data.

I believe that the only way to achieve this is to percent encode binary data yourself and then use `set_query` to explicitly set a URL's query parameters. This is fine, but it doesn't feel right when there's already a built-in system to percent encode data. It's also a bit awkward since all but one of my query parameters are valid UTF-8 and can use the regular `add_pair` interface.

Presumably this isn't a feature that the servo project needs, but unless I'm not understanding how your encoding system works it seems like a fairly arbitrary restriction.

**Comment by SimonSapin** [comment]
This module implements the specification at https://url.spec.whatwg.org/#application/x-www-form-urlencoded , which is designed to encode and decode key/value pairs of Unicode strings. One of the steps is converting the strings to/fom bytes using a character encoding that defaults to UTF-8, but can be overridden. (In Rust, encoding a string to UTF-8 bytes happens to be a no-op because the memory representation of `&str` happens to be UTF-8.)

While it wouldn’t be too hard to add a `add_bytes_pair` method that takes `&[u8]` instead of `&str`, it seems to me that it doesn’t belong there.

Why do you need non-Unicode data in there in the first place? If it is Unicode but with another character encoding, use the `Serializer::encoding_override` method (and the `query_encoding` Cargo feature to enable it).

**Comment by michael-younkin** [comment]
Thanks for the response!

Yeah, unfortunately I actually do have to send arbitrary binary data (ie. not a string). Specifically, it's a SHA1 hash. I can't change the protocol (I'm implementing the BitTorrent tracker protocol) so I'm not able to convert it to something more conventional (like UTF-8) first. I saw `Serializer::encoding_override`, but I think that still doesn't solve my problem (I might be able to encode the hash as hexadecimal UTF8 and then decode that back into binary with some sort of custom encoder, but that's definitely more of a hack than I'd like).

I do understand if serializing arbitrary bytes is beyond the scope of this project. I know it's probably an unusual request. From my perspective, it is unfortunate though, because this seems to be the only mostly complete URL library for Rust that I could find, and everything else about it is perfect for my purposes.

I ended up writing my own `QueryParamBuilder` since all I needed to do was percent encode the data. It's unfortunate that the algorithm had to be duplicated though.

**Comment by alexander-irbis** [comment]
Typically, the binary data should be encoded and decoded using base64

**Comment by michael-younkin** [comment]
@alexander-irbis I understand that, but if you look at what I wrote you'll see that base64 doesn't help in this case.

@SimonSapin You haven't said anything, so I assume you're either busy or waiting for more input? If it's the latter, note that Python's urllib supports percent encoding and decoding both bytes and UTF8 strings (see [urllib.parse.urlencode](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlencode): it allows the user to pass in a mix of `str` (UTF8) and `bytes` (binary) objects, and it encodes accordingly). Obviously another language supporting it doesn't mean this library should support it, but my point is that the behavior is not unprecedented.

**Comment by untitaker** [comment]
IMO Python's urllib module isn't a role model wrt how to design APIs that are easy to use correctly, but in this particular case I'd agree that accepting bytes for query-encoding is a sensible thing to do. However, the new method should probably come with a big warning in the docs that the other methods should be used whenever possible to avoid accidental spec violations.

**Comment by angusturner** [comment]
Any update on this? I am having the same issue attempting to implement the Bittorrent protocol. i.e. the SHA1 hash is not UTF8, and thus cannot be percent encoded by the Serializer :(

It seems that an older version of this library had  a FORM_URLENCODED_ENCODE_SET that would possibly do the trick?

**Comment by kkartaltepe** [comment]
I also ran across this problem.  (Rust BitTorrent implementations seem to be popular!)

>'d agree that accepting bytes for query-encoding is a sensible thing to do. However, the new method should probably come with a big warning

A method that allows for filling in arbitrary bytes, while useful, should probably be `unsafe` unless there is a way to prevent calling the stringify-ing calls on it later on probably at runtime.

Currently there are `query` and `set_query` which operate on the entire `query`-part and `query_pairs`/`mut_query_pairs` which operate on strings, but there is no set that operate on only `percent_encoded` values (a middle ground between the two provided operations). 

And while operating with `query_set` or even `Url::parse` works for me, having a percent_encoded level would be nice for this. One key point is both of these functions are inherently unsafe in the current implementation since they do not validate percent_encoded values as valid utf-8. See this example program for some real strangeness.
```rust
extern crate url;

pub fn main() {
	let url_test = url::Url::parse("http://www.google.com/?query=%80%FF&q2=ABC").unwrap();
	for (k,v) in url_test.query_pairs() {
		println!("{} : {:?}({})", k, v, v.len());
	}
}
```

**Comment by kkartaltepe** [comment]
Ahh after looking into it I see it is replacing these with the `from_utf8_lossy` function so the invalid bytes are being filled with the `U+FFFD REPLACEMENT CHARACTER` and while i guess this makes it safe it certainly makes it less usable as "valid" parts of the query being silently eaten.

**Comment by SimonSapin** [comment]
Several levels of abstraction need to be separated:

* As far as the URL parser is concerned, the *query* component of an URL is a single arbitrary string. It doesn’t know about key/value pairs. You can access that string with `Url::query` or modify it with `Url::set_query`. When processing a query string in their input (which is Unicode `&str`), the URL parser and `set_query` will let through ASCII printable characters except ` "#<>~ ` unchanged; everything else is encoded to UTF-8 then percent-encoded. In particular, `%` is left unchanged, so **the input can include portions that are already percent-encoded**. These portions, when percent-decoded, are **do not have to be well-formed UTF-8**.

* Separately, the `url` crate also provides a `percent_encoding` module. For example, you can decode a non-Unicode query string like so:
   ```rust
   let query: Cow<[u8]> = percent_decode(url.query().unwrap_or("")).into();
   ```
   If you do want Unicode, there’s also a convenience method:
   ```rust
   let query: Cow<str> = percent_decode(url.query().unwrap_or("")).decode_utf8_lossy();
   ```
   The `*_lossy` decoding methods replace ill-formed UTF-8 byte sequences with U+FFFD.

* On top of all this, the `url` crate also also provides support for a format called [`application/x-www-form-urlencoded`](https://url.spec.whatwg.org/#application/x-www-form-urlencoded). This format encodes key/value pairs into single ASCII string, using precent-encoding and `&` / `=` separators. The code for this resides in the `form_urlencoded` module, which can be used independently or through the `Url::query_pairs` or `Url::query_pairs_mut` convenience methods.

   In the WHATWG specification and in the rust-url implementation of `application/x-www-form-urlencoded`, the keys and values are both Unicode. I understand that the Bittorrent protocol uses something like `application/x-www-form-urlencoded` with non-Unicode values, but today I am declaring this out of scope for rust-url.

   However, rust-url does expose the [`url::form_urlencoded::byte_serialize`](https://docs.rs/url/1.4.0/url/form_urlencoded/fn.byte_serialize.html) which is one of the relevant building blocks.

----

Given the above, my recommendation for Bittorrent implementations that want to use rust-url is to use something like this (untested):

```rust
use url::Url;
use url::form_urlencoded::byte_serialize;
use url::percent_encoding::prercent_decode;

// This does not decode '+' as ' '.
// Doing that or avoiding the Vec allocation is left as an exercise to the reader.
pub fn decode_bytes_pairs(input: &str) -> Vec<(Cow<[u8]>, Cow<[u8]>)> {
    let mut pairs = Vec::new();
    for part in input.split('&') {
        if part.is_empty() {
            continue
        }
        let mut split2 = part.splitn('=');
        let key = split2.next().unwrap();
        let value = split2.next().unwrap_or("");
        debug_assert!(split2.next().is_none());
        pairs.push((prercent_decode(key).into(), prercent_decode(value).into()))
    }
    pairs
}

pub fn encode_bytes_pairs<I>(pairs: I) -> String
where I: IntoIterator, I::Item: AsRef<[u8]>
{
    let mut query = String::new();
    let mut iter = pairs.into_iter();
    if let Some((first_key, first_value)) = iter.next() {
        write_pair(&mut query, first_key.as_ref(), first_value.as_ref());
        for (key, value) in iter {
            query.push('&');
            write_pair(&mut query, key.as_ref(), value.as_ref());
        }
    }
    query
}

fn write_pair(query: &mut Strig, key: &[u8], value: &[u8]) {
    query.extend(byte_serialize(key));
    query.push('=');
    query.extend(byte_serialize(value));
}
```

If you want to maintain in an separate crate feel free. But I don’t think it quite belongs in rust-url.

**Comment by kkartaltepe** [comment]
I am currently using something akin to the example you have provided and it works quite well. `Url` does provide all the building blocks to make it simple to implement. While unfortunate you dont feel it belongs in rust-url I'm sure other rustlings like myself who stumble upon this issue will find it useful.

Thanks for such a comprehensive answer to the issue!

**Comment by iwinux** [comment]
In case someone else runs into this issue again - this is what you might need in respect to the righteous WHATWG spec:

```rust
fn extract_info_hash(raw_query: &str) -> Option<String> {
    static INFO_HASH_PATTERN: OnceLock<Regex> = OnceLock::new();

    // clone: https://docs.rs/regex/latest/regex/#sharing-a-regex-across-threads-can-result-in-contention
    let pattern = INFO_HASH_PATTERN
        .get_or_init(|| Regex::new(r"info_hash=(?P<value>[^&]+)").unwrap())
        .clone();

    pattern
        .captures(raw_query)
        .and_then(|captured| captured.name("value"))
        .map(|m| m.as_str().as_bytes())
        .map(|value| percent_decode(value).collect::<Vec<_>>())
        .map(hex::encode)
}
```
