### ISSUE TITLE
Index out of bounds panic when using join()

### ISSUE THREAD

**Issue by pyfisch** [servo/rust-url#224]
``` rust
extern crate url;

use url::Url;

fn main() {
    let mail_proto: Url = "mailto:".parse().expect("protocol parses");
    let mail: Url = mail_proto.join("webmaster@example.com").expect("mail parses");
    println!("{}", mail);
}
```

panics with: 

```
   Compiling playground v0.0.1 (file:///playground)
     Running `target/debug/playground`
thread 'main' panicked at 'index out of bounds: the len is 7 but the index is 7', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/url-1.2.0/src/lib.rs:1155
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: Process didn't exit successfully: `target/debug/playground` (exit code: 101)
```
- Playground: http://play.integer32.com/?gist=eccf4fd3633c1d712f6a34c275768d56
- Gist: https://gist.github.com/anonymous/eccf4fd3633c1d712f6a34c275768d56

By the way how to do I parse an email address without `mailto:` scheme provided?

**Comment by Manishearth** [comment]
Was fixed by https://github.com/servo/rust-url/pull/242

You probably don't want to use this crate for email parsing. It doesn't use an email parser for parsing `mailto:`, because mailto URIs just need to be valid URIs, not valid emails.
