### ISSUE TITLE
Support URL canonicalization/normalization

### ISSUE THREAD

**Issue by sanmai-NL** [servo/rust-url#229]
This is a feature request. For a project I need to iterate over the path segments that make up the path component of a URL, relative to a base URL. 

It appears this library currently (at 1.2.1) does not help with this. To do it manually, I think I must [canonicalize](https://en.wikipedia.org/wiki/URL_normalization) the URLs in the pair so that I can directly compare as strings their path components and determine whether/where they diverge or extend.

See [these tests](https://github.com/apache/httpclient/blob/28a6d5c481f31cee11585493826322ac210e2aaf/httpclient5/src/test/java/org/apache/hc/client5/http/utils/TestURIUtils.java#L133-L205) to get a taste of what I mean.

**Comment by SimonSapin** [comment]
With this library, `parsed_base_url.join(str)` parses the given string relatively to the given base URL. Parsing does do *some* normalization along the way. For example (from the first test case you linked), the protocol is ASCII-lowercased and `.` and `..` path segments are resolved.

https://tools.ietf.org/html/rfc3986#section-6 discusses how there are many possible ways to define equivalence and normalization, with a "comparison ladder" although this is not strictly one-dimensional. https://url.spec.whatwg.org/#url-equivalence picks one way, and this library implements it with `PartialEq for Url` (that is, overloading the `==` operator).

Does this do what you want? If not, how precisely?

**Comment by SimonSapin** [comment]
I’ve filed https://github.com/servo/rust-url/issues/461 to have a look at https://github.com/iron/staticfile/pull/90#discussion_r86990576 specifically. Closing as it is unlikely that this crate will provide normalization beyond what is specified in https://url.spec.whatwg.org/, if only because there is no single answer to what the behavior should be.
