### ISSUE TITLE
username() -> Option<&str>?

### ISSUE THREAD

**Issue by ConnyOnny** [servo/rust-url#234]
Hey, just wondering why username() returns an empty string and password() returns None if not set.
This makes my code a little weird:

``` rust
let mut username = parsed_url.username();
if username.is_empty() {
    username = "anonymous";
}
let password = parsed_url.password().unwrap_or("anonymous");
```

If there isn't a good reason for this, I'd like to propose that `username()` should also return an Option.

**Comment by SimonSapin** [comment]
This reflects the data model in the spec:

https://url.spec.whatwg.org/#urls
> A URL’s username is an ASCII string identifying a user. It is initially the empty string.
>
> A URL’s password is either null or an ASCII string identifying a user’s credentials. It is initially null. 

To be honest I don’t know the reason for this difference. @annevk, can you say more? If the username could also be null, I suppose it would be null in `http://example.com/` but still the empty string in `http://example.com@/`.

**Comment by ConnyOnny** [comment]
Some experiments:
````
"http://x.com"
username: ""
password: None

"http://@x.com"
username: ""
password: None

"http://:@x.com"
username: ""
password: Some("")

"http://example.com@/"
thread 'main' panicked at 'invalid url: EmptyHost'
````
This makes it impossible to specify the empty string as a username, as the application will always think, there was no username given at all.

**Comment by annevk** [comment]
You can differentiate between password being present and not, but not with username.

**Comment by SimonSapin** [comment]
@annevk yes, in the model as currently specified in https://url.spec.whatwg.org/#urls. But is there a specific reason it is specified that way?

**Comment by annevk** [comment]
As far as I know that matches user agents and how the syntax works.

**Comment by SimonSapin** [comment]
In fact the standard went in the opposite direction: removing the distinction between no password and an empty password https://github.com/whatwg/url/pull/186

**Comment by blanham** [comment]
@SimonSapin Would that indicate then that password should also not be `Option<&str>`? Also, would you be open to a PR that adds a convenience function getter for `username` (and perhaps `password`, if it is changed to match the standard) that returns an `Option<&str>`? Then you could do this, as @ConnyOnny was proposing:
```
let username = parsed_url.username_as_option().unwrap_or("anonymous");
let password = parsed_url.password_as_option().unwrap_or("anonymous");
```
With the current focus on ergonomics in the community I think it would be a nice addition.
