### ISSUE TITLE
Impl Default for url::Url?

### ISSUE THREAD

**Issue by sanmai-NL** [servo/rust-url#238]
Is this sensible? My need for it arose when trying to make a [`petgraph::graph::Graph`](https://docs.rs/petgraph/0.4.1/petgraph/graph/struct.Graph.html) of `Url` values. I assume it is very trivial but before spending time on a PR, would like to check with you.

**Comment by SimonSapin** [comment]
What would be the default value?

**Comment by sanmai-NL** [comment]
That is the question indeed. It could well be anything and everything. But [`file:///`](file:///) seems to the most minimal, well-understood, cross-platform valid base URL and all in all suitable default value. The semantics of `std::default::Default` are not very strict if I interpret the [doc](https://doc.rust-lang.org/beta/std/default/trait.Default.html) correctly:
> A trait for giving a type a useful default value.

I think I’m convinced of the usefulness of data types such as graphs being able to work with `url::Url` values. Would that convince you? Is this, by the way, the only aspect that should be discussed that you’re aware of?

**Comment by SimonSapin** [comment]
In my opinion, the fact that it’s not obvious what the default value should be is a sign that `Default` should not be implemented.

How does a `Default` impl help with `petgraph`? What default value could make sense in that context? Does it work for you to use `Option<Url>` (which implements `Default` as `None`)?

**Comment by sanmai-NL** [comment]
Well, I would advise to consider the wording of (the rest of) the doc of the `Default` trait. It really just does not put any requirements on the values taken as default, other than it being useful.

The `Option<Url>` trick works, thanks. Any default value could make sense in that context, with preference for the most space efficient ones. For example the default value I proposed would work for constructing a graph via `petgraph` for more people than just me.

For other beginners who end up here searching for the error message, and since you raised the question, some off-topic elaboration. The [Default trait bound](https://github.com/bluss/petgraph/blob/9264b25ba857843b15169e42feb8b6f2d36809d9/src/graph.rs#L1225) on the (only?) methods[<sup>1</sup>](https://docs.rs/petgraph/0.4.1/petgraph/graph/struct.Graph.html#method.extend_with_edges) that can add edges and arcs to a graph seems an ‘unnecessary’ (not judging) design choice made in `petgraph`. It's of course useful to assign default weight to edges, but seems to be required even when all weights are provided in the below example.

```rust
let resource_1_url = Url::parse("file:///1").unwrap();
let resource_2_url = Url::parse("file:///2").unwrap();
let mut resource_graph = Graph::<Url, Option<usize>>::new();
let resource_1 = resource_graph.add_node(resource_1_url);
let resource_2 = resource_graph.add_node(resource_2_url);
resource_graph.extend_with_edges(&[(resource_1, resource_2, None),]);
```

```
error[E0277]: the trait bound `url::Url: std::default::Default` is not satisfied
   --> src/main.rs:102:17
    |
102 | 	resource_graph.extend_with_edges(&[(resource_1, resource_2, None),]);
    | 	               ^^^^^^^^^^^^^^^^^ the trait `std::default::Default` is not implemented for `url::Url`
```

**Comment by SimonSapin** [comment]
I agree that a `Default` impl would not be incorrect per `Default`’s docs, but I don’t agree that having it return `file:///` is particularly useful. So I’d rather not have this impl.

As to space efficiency, I’ve just verified that `size_of::<Url>() == size_of::<Option<Url>>()`. This is because `Url` contains a `String` which (ultimately) contains a `NonZero<*const u8>` pointer that guaranteed to be non-null, so Rust can use null values to represent `None`.

If this `N: Default` bound is unnecessary, have you considered filing an issue on `petgraph` about removing it or adding a different method that doesn’t have it?

**Comment by sanmai-NL** [comment]
@SimonSapin: on your last remark, see my elaboration, that settles it for me. In the end, there may still be some room for improvement in terms of docs and design of `petgraph`, perhaps particularly for novice library users, but we’ll see later.

**Comment by SimonSapin** [comment]
Closing as I’m not convinced there is a change to make to rust-url.

**Comment by vpochapuis** [comment]
Hello, sorry to post on this, (I am not sure whether its a good practice or not to send a message on a closed issue like this). 

I would like to ask if it could be possible to have a Default implementation for `url::Url` with a value of `https://example.com/` ,`http://localhost/` or `http://127.0.0.1/` which are often used in examples a lot on the net as well as on the [Url Standard](https://url.spec.whatwg.org/) which is linked in the documentations. I personally think (is my opinion shared?) they are pretty predictable defaults.

I don't want to be annoying, but just make a suggestion and have feedbacks on why it wouldn't be a good idea if it was the case.

Thank you!

**Comment by valenting** [comment]
I think if we were to choose a default, that choice would still surprise some people. It's probably better not to have a default, especially given the arguments above.
