### ISSUE TITLE
Implement URL spec changes regarding 'percent encode fragments'

### ISSUE THREAD

**Issue by frewsxcv** [servo/rust-url#246]
https://twitter.com/urlstandard/status/807279430490058752

https://github.com/whatwg/url/issues/150

https://github.com/whatwg/url/pull/169

**Comment by frewsxcv** [comment]
Maybe this should be folded into https://github.com/servo/rust-url/issues/163? ¯\_(ツ)_/¯

**Comment by valenting** [comment]
@Manishearth @SimonSapin This is blocking [url-oxidation](https://bugzilla.mozilla.org/show_bug.cgi?id=1318426).

**Comment by Manishearth** [comment]
Fix in #248
