### ISSUE TITLE
Setting the scheme to "file" should fail if there's a host or port

### ISSUE THREAD

**Issue by asajeffrey** [servo/rust-url#278]
The test case:
```rust
    let mut url: Url = "http://localhost:6767/foo/bar".parse().unwrap();
    let result = url.set_scheme("file");
    assert_eq!(url.to_string(), "http://localhost:6767/foo/bar");
    assert_eq!(result, Err(()));
```
should pass, instead it fails with:
```
   (left == right)` (left: `"file://localhost:6767/foo/bar"`, right: `"http://localhost:6767/foo/bar"`)
```
The resulting URL has a `file` scheme, and a host/port, so serialization fails.

**Comment by asajeffrey** [comment]
This is the root cause of https://github.com/servo/servo/issues/15435

**Comment by SimonSapin** [comment]
Should it really fail? This doesn’t match the spec at https://url.spec.whatwg.org/#dom-url-protocol

In this test case:

```html
<a id=a href="http://example.net:8080/foo"></a>
<script>
var a = document.getElementById("a");
a.protocol = "file";
document.write(a.href)
</script>
```

Firefox prints `file:///foo`, Chromium prints `file://example.net:8080/foo`. I think we probably want to do like Firefox and remove the port implicitly.

@annevk Do you think the spec should be changed to remove the port in this case and avoid leaving the URL in an inconsistent state?

**Comment by annevk** [comment]
If you look at scheme state 2.1.3 it seems pretty clear there is a special case. It's not quite failure, but it shouldn't succeed.

**Comment by tmccombs** [comment]
https://url.spec.whatwg.org/#scheme-state
> If url includes credentials or has a non-null port, and buffer is "file", then return.
If I understand this correctly, it means that setting the scheme to file for a URL that has credentials or a port specified should fail.

**Comment by annevk** [comment]
It's a no-op from the perspective of JavaScript, it doesn't throw. That's what I meant with not quite failure.

**Comment by tmccombs** [comment]
You're right @annevk.

**Comment by sanmai-NL** [comment]
@SimonSapin: Similarly, this library behaves counterintuitively when parsing a data URL.
See https://play.rust-lang.org/?gist=032d9d4e7724b68d74efec2daf07df35&version=stable
My reading of this discussion is that @tmccombs's #366 isn't an unreasonable approach in the end. 

In the JavaScript console in the latest Firefox:
```
>> var parser = document.createElement('a');
>> parser.href = "data://localhost:80";
>> console.log(parser.protocol);
 http:
 undefined 

>> console.log(parser.host); 
 undefined

>> console.log(parser.hostname);
 undefined

>> console.log(parser.port); 
 undefined
```
Some weirdness with the protocol component/scheme, but no hostname or port number extracted from a data URL for sure.

**Comment by jdm** [comment]
@sanmai-NL Data URLs do not include the //.

**Comment by sanmai-NL** [comment]
@jdm: I know, a valid example is the counterexample in the Rust playground test case.

**Comment by annevk** [comment]
For a data URL that includes // Firefox is incorrect there as the URL parser doesn't special case data URLs.

**Comment by djc** [comment]
This passes the proposed test, so I'm guessing it can be closed. I added the test in 7b8b8416c3bc0ba1c5565492f39d2d41bea98ba3 just to make sure.
