### ISSUE TITLE
Join clobbers final segment

### ISSUE THREAD

**Issue by sp0** [servo/rust-url#285]
The Url join function appears to remove any trailing content up until the last slash. The following code fails:
```
#[test]
fn test_join() {
    let url = Url::parse("https://example.net/foo/bar").unwrap();
    let url = url.join("baz").unwrap();
    assert_eq!(url.as_str(), "https://example.net/foo/bar/baz");
}
```
Here's the result:
```
assertion failed: `(left == right)` (left: `"https://example.net/foo/baz"`, right: `"https://example.net/foo/bar/baz"`)
```

**Comment by SimonSapin** [comment]
This is working as intended. Trailing slashes are significant. If an HTML document is at `https://example.net/foo/bar.html`, then `<img src="baz.png">` resolves to `https://example.net/foo/baz.png`. If however the base URL is `https://example.net/foo/bar/` (with a trailing slash, which on many servers’ default configuration means an implied `index.html`) or `https://example.net/foo/bar/index.html`, then the image resolves to `https://example.net/foo/bar/baz.png`.

**Comment by sp0** [comment]
Uhuh, I was not expecting those semantics, even after reading the docs. It is probably a failing on my end, but I don't think it would hurt to clear up the documentation of this function. For example, Nodejs called this function [resolve](https://nodejs.org/api/url.html#url_url_resolve_from_to)

> The url.resolve() method resolves a target URL relative to a base URL in a manner similar to that of a Web browser resolving an anchor tag HREF.

**Comment by SimonSapin** [comment]
How does this look? https://github.com/servo/rust-url/blob/7b87128f0a527b021a7fdbd2ef71e1592ef3d769/src/lib.rs#L257-L275

**Comment by dtantsur** [comment]
I understand that it's useful for writing browsers, but could you please create a version of join() for other people? Also +1 to calling it "resolve", this function does not do "join".

**Comment by SimonSapin** [comment]
I’d review a PR adding a new method.

Renaming existing methods is a breaking change, which are very cumbersome since updating various crates that use `url` and are used together needs to be coordinated. Renaming things is far from enough of a reason to justify it.

**Comment by dtantsur** [comment]
Yeah, I get it. Any ideas for a new name then? `append`?

**Comment by SimonSapin** [comment]
Just to make sure:

`Url::join` is the same as `Url::parse`, just with a base URL so that relative URLs are accepted and resolved from that base. The parameter to join doesn’t have to be relative, it can be an absolute URL in which case the base is ignored. And it’s not just a path, all URL components can be set through `join`.

Is this really what you want for this hypothetical new method?

Note that if you only want to append a component to the *path* of an URL, `url.path_segments_mut().unwrap().push("bar")` already exists.

If you do want something more like `join` than pushing a segment, you can also do this today (untested):


```rust
if url.path_segments().map_or(false, |s| s.next_back().unwrap() != "") {
    // No trailing slash, add it
    url.path_segments_mut().unwrap().push("")
}
url.join(something)
```

**Comment by dtantsur** [comment]
Yeah, something like the latter.

**Comment by nox** [comment]
> For example, Nodejs called this function resolve

> Also +1 to calling it "resolve", this function does not do "join".

What is "join" then? There is no join method on URLs in nodejs AFAIK. In which languages is there a join method that ignores whether the slash is present or not?

**Comment by nox** [comment]
Never mind, `join` is indeed a bad name given how `PathBuf::join` behaves. :(
