### ISSUE TITLE
Include method that checks validity of domain name

### ISSUE THREAD

**Issue by clarcharr** [servo/rust-url#287]
For [parse-hosts](https://github.com/clarcharr/parse-hosts/blob/master/src/data_line.rs#L132) I implemented this code by myself, but I think it'd be worthwhile to have in the `url` crate as well.

Essentially, this would be equivalent to calling `Host::parse` without IP parsing or calling `percent_decode` or `domain_to_ascii`.

**Comment by SimonSapin** [comment]
So… what’s left? Only looking for `'\0' | '\t' | '\n' | '\r' | ' ' | '#' | '%' | '/' | ':' | '?' | '@' | '[' | '\\' | ']'` ? Doing this by itself doesn’t make much sense, it’s intended to work with `domain_to_ascii`:

http://www.unicode.org/reports/tr46/#UseSTD3ASCIIRules
> If UseSTD3ASCIIRules=false, then the validity tests for ASCII characters are not provided by the table status values, but are implementation-dependent. For example, if an implementation allows the characters [\u002Da-zA-Z0-9] and also the underbar ( _ ), then it needs to use the table values for UseSTD3ASCIIRules=false, and test for any other ASCII characters as part of its validity criteria. These ASCII characters may have resulted from a mapping: for example, a U+005F ( _ ) LOW LINE (underbar) may have originally been a U+FF3F ( ＿ ) FULLWIDTH LOW LINE.

**Comment by SimonSapin** [comment]
Closing for lack of response, feel free to reopen or comment.
