### ISSUE TITLE
Showing off rust-url and Rust – command line tool for parsing URLs.

### ISSUE THREAD

**Issue by piotr-dobrogost** [servo/rust-url#289]
I've been looking for command line Linux tool able to parse URLs. Surprisingly I could not find any. There are several questions asking how to parse URL on the command line/in shell on Stackoverflow and most *answers* suggest using sed/awk/bash's string-splitting operators for this which is just plain wrong. Then I found this project. I think if you made the simplest possible command line tool utilizing rust-url that would be great way of showing off rust-url and Rust in general. It would be enough to take URL as a string on standard input and print all its components on standard output. Components such as querystring could/should be parsed as well.

**Comment by SimonSapin** [comment]
Such a tool should be straightforward to build on top of rust-url, but I don’t think it belong in this repository.

**Comment by piotr-dobrogost** [comment]
Fair enough and thanks for quick response. Now, at least I will be able to refer people asking here and tell them they should write the tool themselves.
