### ISSUE TITLE
url_serde: Update to serde 1.0 and make use of serde remote-derive

### ISSUE THREAD

**Issue by maximih** [servo/rust-url#295]
Serde 1.0 was just released and has a new nice feature that we can make use of: [remote-derive](https://serde.rs/remote-derive.html). This would improve the ease of use for url_serde.

**Comment by maximih** [comment]
I will try to find some time to work on this during the weekend.

**Comment by SimonSapin** [comment]
@nox Is there a plan for moving Servo’s dependency graph to serde 1.0?

**Comment by nox** [comment]
I'll probably look at that next week.
