### ISSUE TITLE
Implement `Display` for `Host` and `HostAndPort`

### ISSUE THREAD

**Issue by brson** [servo/rust-url#300]
Probably using the obvious serialization for "host:port". Looks like `HostAndPort` impl needs to be parameterized over `S: Display`.

**Comment by SimonSapin** [comment]
For IPv6 addresses, using `[]` brackets is necessary to distinguish `:` within an address and `:` separating an address and port number. `Display for Host` already does this.

**Comment by luisbg** [comment]
Is anybody working on this?

**Comment by SimonSapin** [comment]
I kinda regret making `HostAndPort` a custom type rather than a tuple and I think making it implement `Display` just because is kind of cargo-culting, but whatever.

**Comment by luisbg** [comment]
Cool to see this added. Thanks @SimonSapin
