### ISSUE TITLE
Drop old serde support and move serde 1.0+ support in-crate

### ISSUE THREAD

**Issue by brson** [servo/rust-url#303]
Having serde support in its own crate is not the ideal pattern for serde. It would be better for the `serde` feature to be for modern `serde`. Changing this though requires a major version bump.

@dtolnay has a plan for getting serde 1.0 support in-crate using a slightly uglier pattern in the meantime.

**Comment by dtolnay** [comment]
Moving Serde support in-crate is tracked in #304 so this is just tracking dropping the old Serdes.

**Comment by nox** [comment]
This was done in `master`.
