### ISSUE TITLE
Implement Debug for many types

### ISSUE THREAD

**Issue by brson** [servo/rust-url#305]
We generally implement Debug for all types in libraries that are intended for general use.

Add `Debug` for HostAndPort, ParseOptions, PathSegmentsMut, SocketAddrs, UrlQuery, ByteSerialize, Parse, ParseIntoOwned, Serializer, `*_ENCODE_SET`, PercentEncode, PercentDecode.

**Comment by SimonSapin** [comment]
Guideline question: some of these types only exist (or are only public) because the language does not support `-> impl Iterator<Item=Foo>` yet. When it does, will it be recommended that everything uses `-> impl Iterator<Item=Foo> + Debug`?

**Comment by dtolnay** [comment]
Which types are you considering replacing with `impl Trait`? In any case, I filed https://github.com/brson/rust-api-guidelines/issues/60 to follow up on a guideline.

**Comment by brson** [comment]
Since these do exist today, it is reasonable that they implement Debug, right?

**Comment by clarcharr** [comment]
Moving to `impl Iterator` would be a breaking change anyway, so it doesn't hurt to implement `Debug` for 1.0.

**Comment by TheFirstLairron** [comment]
I would be willing to help out with implementing these. Is there anything I would need to know before hopping in?
