### ISSUE TITLE
Modify `define_encode_set` to support private definitions

### ISSUE THREAD

**Issue by brson** [servo/rust-url#307]
Right now all encode sets must be explicitly `pub`. Generally such macros should have a grammar that accepts non-pub definitions.

It doesn't look like the existing grammar supports this extension though:

```
define_encode_set! {
    /// This encode set is used in the URL parser for query strings.
    pub QUERY_ENCODE_SET = [SIMPLE_ENCODE_SET] | {' ', '"', '#', '<', '>'}
}
```

There's no other keyword there besides `pub`. Seems like this definition would be better if you had to type like `pub struct QUERY_ENCODE_SET`.

So fixing this might require adding two rules and basically deprecating the existing rule? Not sure.

**Comment by SimonSapin** [comment]
As discussed in https://github.com/servo/rust-url/issues/298#issuecomment-299402826 this is a very niche feature, so extending it seems low value. In particular it doesn’t seem worth adding new APIs and deprecating old ones, to me.

**Comment by brson** [comment]
@SimonSapin ok, sgtm.
