### ISSUE TITLE
parse_ipv6addr: add some bounds checking on indexes

### ISSUE THREAD

**Issue by lucab** [servo/rust-url#334]
Capturing my comment from https://github.com/servo/rust-url/pull/294#discussion_r115594882.

`parse_ipv6addr` does a bit of index juggling when decompressing input, and it may benefit from some bound checking to ensure no index underflow/overflow will induce a panic there at runtime.

This exists in current master [here](https://github.com/servo/rust-url/blob/b4d74000f1f70d4d942e92f75e7a7c4eb2c42341/src/host.rs#L476-L486), but it is likely going to be changed by #294.

**Comment by SimonSapin** [comment]
Closing as this doesn’t seem very actionable. Please comment here or open a new issue if there is a specific test case that panics where it shouldn’t.
