### ISSUE TITLE
idna::uts46::find_char loops forever on '\u{10fffe}'

### ISSUE THREAD

**Issue by ilianaw** [servo/rust-url#352]
I don't think this affects most normal usage of the idna crate, but using quickcheck in a project I'm working on found that calling `idna::domain_to_ascii("\u{10fffe}")` loops forever in `idna::uts46::find_char`.

The issue seems to be that `'\u{10fffe}'` is in the last range in `uts46_mapping_table.rs`. The loop within `find_char` reaches a point where `min = TABLE.len() - 2` and `max = TABLE.len() - 1`. This causes `mid == min` for all future iterations of the loop.

The following patch fixed the specific issue but I'm not convinced it's correct. Tests pass, though.

```diff
diff --git a/idna/src/uts46.rs b/idna/src/uts46.rs
index eef531d..007086c 100644
--- a/idna/src/uts46.rs
+++ b/idna/src/uts46.rs
@@ -54,7 +54,7 @@ fn find_char(codepoint: char) -> &'static Mapping {
     while max > min {
         let mid = (min + max) >> 1;
         if codepoint > TABLE[mid].to {
-           min = mid;
+            min = mid + 1;
         } else if codepoint < TABLE[mid].from {
             max = mid;
         } else {
```

**Comment by behnam** [comment]
The loop here is now replaced by `binary_search_by()`.

Fixed by https://github.com/servo/rust-url/commit/e5f7dfcb89e05cf1e795cf7d56c8d60c75b3c903
