### ISSUE TITLE
Percent encode set that encodes $ as %24?

### ISSUE THREAD

**Issue by golddranks** [servo/rust-url#353]
I'm using `rust-url` to percent encode the username and password in my `postgresql://username:password@domain/dbname` style URL. However, my password contains a special character `$`, and no one of the percent encoding sets provided by this crate seems to encode that.

`$` is considered a "Reserved Character" ( https://tools.ietf.org/html/rfc3986#section-2.2 ), so I think it should be reasonable to encode it when it isn't used as a delimiter. I don't know of any current use of it as a delimiter in URLs, but the `libpq` that parses the URL complains about it, and accepts the password only as fully encoded.

Maybe there could be a `STRICT_ENCODE_SET` that would encode each of the reserved characters:

      reserved    = gen-delims / sub-delims

      gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"

      sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
                  / "*" / "+" / "," / ";" / "="

**Comment by SimonSapin** [comment]
Your crate can define its own encode set: https://docs.rs/url/1.5.0/url/macro.define_encode_set.html
