### ISSUE TITLE
`tests/unit.rs` broken on nightly builds

### ISSUE THREAD

**Issue by behnam** [servo/rust-url#371]
Travis: https://travis-ci.org/servo/rust-url/jobs/248944414

Example error:

```
error[E0560]: struct `__test::test::TestDesc` has no field named `allow_fail`
  --> tests/unit.rs:20:1
   |
20 | / fn size() {
21 | |     use std::mem::size_of;
22 | |     assert_eq!(size_of::<Url>(), size_of::<Option<Url>>());
23 | | }
   | |_^ `__test::test::TestDesc` does not have this field
```

I think it's caused by `tests/unit.rs` having test harness enabled, and the test internals having changed and not conflicting `rustc-test` package used here.

I'm not sure what's the best option for a fix:
* Disabling harness for `unit.rs` and copying in boilerplate to get the tests running; or
* Updating `rustc-test` to make it compatible.

What do you think, @SimonSapin ?

**Comment by SimonSapin** [comment]
I think we should make `rustc-test` use https://crates.io/crates/rustc_version to conditionally compile and work with compiler that do or do not include the `allow_fail` field.
