### ISSUE TITLE
Parsing the hostname "xn--" returns an empty hostname, but doesn't throw an error when a hostname is required

### ISSUE THREAD

**Issue by MJDSys** [servo/rust-url#373]
Basically, ```assert_eq!(Url::parse("ftp://xn--"), Url::parse("ftp:///"));``` fails.  It seems even though idna parsing produces an empty host, it's still not considered empty and a valid Url is constructed instead of returning an error.

Is this the expected behaviour?  Or should the empty host check not take into account idna processing.

**Comment by rmisev** [comment]
It was URL spec issue. Now fixed in https://github.com/whatwg/url/pull/497

**Comment by djc** [comment]
This should be fixed by 6b05499d3f42f3522fb549838b80148a4cbdce23.
