### ISSUE TITLE
include text of licenses into sub-crates

### ISSUE THREAD

**Issue by ignatenkobrain** [servo/rust-url#376]
So archive on crates.io will have text of license

**Comment by SimonSapin** [comment]
I might care about this enough to take a pull request

**Comment by ignatenkobrain** [comment]
@SimonSapin I would send it, but I'm not sure whether you would accept simple symlink or you want to support windows where FS doesn't support symlinks, so it requires full copy ;)

**Comment by SimonSapin** [comment]
And `cargo publish` packages each crate independently, I don’t know how it would deal with symlinks to outside the package.
