### ISSUE TITLE
enum deserialization panics on urls

### ISSUE THREAD

**Issue by Korvox** [servo/rust-url#387]
I have a giant Enum for a bunch of disparate Json fields:

```rust
#[derive(Deserialize)]
pub enum Claim {
    Name(String),
    FamilyName(String),
    GivenName(String),
    MiddleName(String),
    Nickname(String),
    PreferredUsername(String),
    #[serde(with = "url_serde")]
    Profile(Url),
    #[serde(with = "url_serde")]
    Picture(Url),
    #[serde(with = "url_serde")]
    Website(Url),
    Gender(String),
    Birthdate(String),
    Zoneinfo(String),
    Locale(String),
    UpdatedAt(u64),
    Email(Email),
}

#[derive(Debug, Validate, Deserialize)]
pub struct Email {
    #[validate(email)]
    pub address: String,
}
```
The deserialize macro is panicking on the Urls here. If I remove them, this passes the RLS and cargo check. I'm using url_serde just fine in structs elsewhere, though:

```rust
#[derive(Deserialize)]
struct Link {
    rel: String,
    #[serde(with = "url_serde")]
    href: Url,
}
```
What is going on here?

**Comment by jdm** [comment]
I suspect you need `Website(#[serde(with = "url_serde")])` instead.

**Comment by Korvox** [comment]
Yep that does it, its undocumented though, and with proc_macros the compiler gives the most uninformative errors. Want me to add a section to the docs mentioning enums? Since most users never need to use the serde(with) syntax on external types they may not know of this interaction until they are trying to serialize URLs.

**Comment by nox** [comment]
This is documented in serde, which specifies how `#[serde(with)]` is supposed to be used.
