### ISSUE TITLE
Round-trip parsing for a URL string results in different outcomes

### ISSUE THREAD

**Issue by frewsxcv** [servo/rust-url#391]
* parsing `"b:/.//"` into a URL becomes `"b://"`
* parsing `"b://"` into a URL becomes `"b:///"`

the intermediary state here seems off to me

seems like it should go straight from`"b:/.//"` to `"b:///"`

```rust
extern crate url;

fn main() {
    let parsed = url::Url::parse("b:/.//").unwrap();
    let as_str = parsed.as_str();
    let parsed2 = url::Url::parse(as_str).unwrap();
    assert_eq!(parsed, parsed2);
}
```

**Comment by frewsxcv** [comment]
Found via https://github.com/servo/rust-url/pull/392

**Comment by nox** [comment]
@frewsxcv Do you remember what the spec says about this?

**Comment by nox** [comment]
Safari parses both as `b://`.

**Comment by qsantos** [comment]
This looks like this is the same bug as https://github.com/servo/rust-url/issues/799, which was fixed by https://github.com/servo/rust-url/pull/817. At any rate, the assertion from the code example now passes.
