### ISSUE TITLE
[Question] How to deserialize Vec<Url>

### ISSUE THREAD

**Issue by hh9527** [servo/rust-url#420]
```rust
use url::Url;

#[derive(Debug, Deserialize)]
struct Foo {
    #[serde(with = "url_serde")] // this works
    some_url: Url,

    #[serde(with = "url_serde")] // this does not work
    urls: Vec<Url>
}
```

**Comment by clarcharr** [comment]
You currently can't use `with` this way; see serde-rs/serde#723.

**Comment by SimonSapin** [comment]
Support for `Vec<Url>` probably needs to be added specifically to `url_serde`, similar to how it supports `Option<Url>` today.

**Comment by SimonSapin** [comment]
url 2.0 will support serde 1.x directly (and serializing `Vec<Url>` should "just work"), without the url_serde crate. Therefore the url_serde crate will likely not get more features.

**Comment by waf** [comment]
For anyone else finding this issue via Google, you can enable serde support for urls by enabling the `"serde"` feature:

```toml
url = { version = "2", features = ["serde"] }
```
