### ISSUE TITLE
Serialize structs to query params

### ISSUE THREAD

**Issue by xoac** [servo/rust-url#429]
Hi,
 there is quite fine crate that allow Serialize struct into query -- [query_params](https://docs.rs/query_params/0.1.0/query_params/) 

This works quite well with this lib, maybe separate just parameters part or make another module would be a good idea. More see [here](https://github.com/NotBad4U/query_params/issues/1) 

It's just an idea.

**Comment by SimonSapin** [comment]
Hi. I don’t understand what this issue is about exactly. If the two libraries already work well together, what else is there to do? Are you proposing new APIs in the `url` crate? What would they look like?

**Comment by SimonSapin** [comment]
I think this functionality is out of scope for this crate / repository. Consider pursuing https://github.com/NotBad4U/query_params/issues/1 instead.

**Comment by tobz1000** [comment]
Recently I've had a need(/want) for this too - so I made a crate which converts serializable types (i.e implementing `serde::Serialize`) to the format required by `Url::parse_with_params`:
https://crates.io/crates/url_params_serializer

I may also add a Deserializer in future, which could be used with the return value of `Url::query_pairs` or similar.

**Comment by srid** [comment]
For Deserializer, `serde_qs` works:

https://docs.rs/serde_qs/latest/serde_qs/
