### ISSUE TITLE
make userid optional in url string

### ISSUE THREAD

**Issue by Dowwie** [servo/rust-url#440]
parse won't recognize a password in a url string if a userid isn't provided as well.  There are systems such as Redis that do not require a username but rather only an authentication password/token.  Consequently, a redis connection string omits user_id.  

Example:

```rust
extern crate url;

fn main() {
    let input = "redis://password@localhost:6379";
    let x = url::Url::parse(input).unwrap();
    
    println!("host: {:?}", x.host());
    println!("host: {:?}", x.port());
    println!("password: {:?}", x.password());  // is None
```

**Comment by badboy** [comment]
See my comment in mitsuhiko/redis-rs#144: `rust-url` is working as expected. The password is _always_ after a colon, an empty user field is allowed.

**Comment by SimonSapin** [comment]
Right, `redis://password@localhost:6379` has a user name whose value is `password` and doesn’t have a password. Try `redis://:password@localhost:6379`? (To get a user name that is the empty string)
