### ISSUE TITLE
Migrate to encoding_rs crate?

### ISSUE THREAD

**Issue by talklittle** [servo/rust-url#444]
Servo has migrated from [rust-encoding](https://github.com/lifthrasiir/rust-encoding) to [encoding_rs](https://github.com/hsivonen/encoding_rs).

Is the plan to do the same migration for `rust-url`, when using the `query_encoding` feature?

**Comment by SimonSapin** [comment]
The query encoding feature was designed for Servo, but Servo hasn’t been using it so far. And yes, I’d prefer not to bring rust-encoding back into Servo’s dependency graph, so that functionality becomes needed we’ll consider adding a separate Cargo flag.

**Comment by talklittle** [comment]
Thanks for the answer. I am interested in this feature for https://github.com/servo/servo/issues/13238

**Comment by hsivonen** [comment]
[Link to old PR on the same topic](https://github.com/servo/rust-url/pull/262) (of interest particularly for efficient `Cow` usage).

**Comment by nox** [comment]
There is no encoding crate at all used in servo anymore.
