### ISSUE TITLE
Add with_query, with_fragment, etc

### ISSUE THREAD

**Issue by vitiral** [servo/rust-url#447]
## Proposal
Add functions like:

```
fn with_attr(&self) -> Self
```

to compliment the `set_attr` functions. Functions to implement:

- `with_query`
- `with_fragment`
- `with_path`
- `with_port`
- `with_host`
- `with_ip_host`
- `with_password`
- `with_username`
- `with_scheme`

## Problem

Functions like [`set_query`](https://docs.rs/url/1.7.0/url/struct.Url.html#method.set_query) exist, but creating a new url requires the user to do:

```
let mut query = base.clone();
query.set_query("foo");
query
```

It would be much more convenient to do:

```
base.with_query("foo")
```

**Comment by SimonSapin** [comment]
Thank you for your proposal. This looks like a significant increase in API surface for only slightly more convenient usage, so I think I’d rather not take this.
