### ISSUE TITLE
Releases not available on Crates.io

### ISSUE THREAD

**Issue by davidarmstronglewis** [servo/rust-url#448]
Hi there, not sure if this is intentional or no, but why does crates.io not have the releases available here available there? Not a blocker since I can just require the tagged repo directly, but it doesn't feel right to be doing that.

Let me know if I'm missing something or what.
Thanks!

**Comment by cbrewster** [comment]
@davidarmstronglewis the crate is listed as `url` on crates.io https://crates.io/crates/url

**Comment by davidarmstronglewis** [comment]
Nope, you're right - I was trying to get at url_serde and didn't pay enough attention. My bad.
