### ISSUE TITLE
cannot_be_a_base contains negation in the name

### ISSUE THREAD

**Issue by kornelski** [servo/rust-url#449]
Checking whether URL can be a base leads to an odd double negation:

```rust
if !url.cannot_be_a_base() 
```

Have you considered renaming this method?

**Comment by SimonSapin** [comment]
This name is based on a spec concept: https://url.spec.whatwg.org/#url-cannot-be-a-base-url-flag

**Comment by kornelski** [comment]
I see it's nice to have it the same name as the spec, when you're the implementor and/or need to double-check behavior in the spec. But WHATWG specs have their own quirky ways of stating things, and this one seems to be merely a shortcut in the WHATWG spec to avoid having to mention "initialize can-be-a-base flag to true" in a few places :)

However, from my perspective of a library user the cannot-be-a-base flag is not a well-known meaningful concept. It's just strange. It seems to go against general best practice of avoiding negations in method names. I've filed this bug because I've noticed this method re-exported in documentation of another library, and I thought it was a mistake.

It does leave it unclear whether negation means can-be-a-base or may-or-may-not-be-a-base.

**Comment by dekellum** [comment]
I would imagine that a PR with the simple addition of `Url::can_be_a_base`, implemented by negating `cannot_be_a_base` would be reasonably considered, as a minor ergonomics win with no breaking change?

**Comment by kornelski** [comment]
I've stumbled upon it when trying to use [ammonia](https://crates.rs/crates/ammonia), which is an HTML sanitiser that rewrites relative URLs to absolute. To configure it I needed to know which URLs "can be a base".

```rust
            if let Ok(url) = Url::parse(url) {
                if !url.cannot_be_a_base() {
                    return UrlRelative::RewriteWithBase(url);
                }
            }
```

**Comment by SimonSapin** [comment]
Is that useful to do? If I remember correctly, running the parser with a base URL that has the cannot-be-a-base flag is the same as running it without a base at all.

**Comment by SimonSapin** [comment]
Closing as the name refers to a spec concept that also includes the negation in its name, and it feels doubtful that good reasons to use this API directly in the first place are common. Feel free to comment further though.
