### ISSUE TITLE
incomplete percent-encoding should be an error

### ISSUE THREAD

**Issue by pchampin** [servo/rust-url#452]
```rust
    assert!(Url::parse("http://a/%").is_err());
    assert!(Url::parse("http://a/%a").is_err());
    assert!(Url::parse("http://a/%ax").is_err());
```
The three assertions above panic, while according to the spec they should pass.

**Comment by SimonSapin** [comment]
What the spec calls a [validation error](https://url.spec.whatwg.org/#validation-error) does not cause the parser to return a failure. It’s more like a warning.

**Comment by pchampin** [comment]
Right, my bad... Sorry for the noise
