### ISSUE TITLE
Move the url::quirks module to Servo

### ISSUE THREAD

**Issue by SimonSapin** [servo/rust-url#460]
Servo’s `components/script/dom/urlhelper.rs` is likely its only user, it’s somewhat out of place in rust-url.

Can all of `url::quirks` be reproduced with only the public APIs of `url`?

**Comment by SimonSapin** [comment]
> Can all of `url::quirks` be reproduced with only the public APIs of `url`?

The answer to that one is: no.

**Comment by lucacasonato** [comment]
[Deno](https://github.com/denoland/deno/tree/main/ext/url) and [`rust-urlpattern`](https://github.com/denoland/rust-urlpattern) both use the quirks module too. It would be great to keep this in the `url` crate.

**Comment by valenting** [comment]
Thanks for the info. Seems like we should keep it then.
