### ISSUE TITLE
Consuming version of parse

### ISSUE THREAD

**Issue by vorner** [servo/rust-url#471]
Hello

Sometimes, I have a `String` with the url available (not just `&str`). Would it make sense to be able to consume that instead of allocating a new one internally? Would that be possible?

**Comment by SimonSapin** [comment]
It might be possible but I don’t know if it would often be beneficial: the string inside `Url` rarely ends up being exactly the same as the input. Regardless, every single step of the parser (which is already non-trivial) would need to keep track of whether the new string differs from the input. So in my opinion the high implementation and maintenance complexity cost for questionable gains makes this not worth trying.

**Comment by vorner** [comment]
You seem to hint at „keep the old one if it doesn't change and allocate new if it does“. My idea was actually doing it in-place if possible. In case the length of every prefix could only shrink, it could be done I think ‒ but maybe my idea is naïve (I certainly didn't study the RFC in too much detail). I agree that doing something very complex just to save one allocation is probably not worth it.

**Comment by vorner** [comment]
Then it's probably not worth the complexity.
