### ISSUE TITLE
Add documentation for (de)serializing enum variants

### ISSUE THREAD

**Issue by bestouff** [servo/rust-url#501]
Let's say I have this `enum`:
```rust
#[derive(Serialize, Deserialize)]
enum Test {
    A(Url, OtherType),
}
```
The documentation is missing for writing this type correctly - there's probably a magic incantation about `#[serde(with = "url_serde")]` somewhere but I couldn't find it easily.

**Comment by jdm** [comment]
The documentation exists in the url_serde crate: https://docs.rs/url_serde/0.2.0/url_serde/#how-do-i-use-a-data-type-with-a-url-member-with-serde

**Comment by jdm** [comment]
Actually, I guess it's not explicit. You should be able to write `A(#[serde(with = "url_serde")] Url, OtherType)`, I think?

**Comment by bestouff** [comment]
Thanks. How about adding #502 to help a bit more ?

**Comment by nox** [comment]
`url_serde` is gone now, you'll be able to use serde 1.0 in url 2.0.

**Comment by bestouff** [comment]
Thanks !
