### ISSUE TITLE
percent-encoding: `%` character not getting escaped

### ISSUE THREAD

**Issue by vi** [servo/rust-url#503]
For example, for this:

```rust
extern crate percent_encoding; // 1.0.1;

fn main() {
    println!("{}", percent_encoding::percent_encode(
        b"%20 %20",
        percent_encoding::USERINFO_ENCODE_SET,
    ))
}
```

I get `%20%20%20`.

I except any percent encoding to be reversibe and `%` itself being encoded in any mode.

**Comment by SimonSapin** [comment]
This crate implements the algorithm https://url.spec.whatwg.org/#percent-encoded-bytes which is designed to deal with input that may already be partially be percent-encoded (and should not be double-encoded) as well as that may contain non-ASCII or reserved characters that need to be percent-encoded.

It is not designed to faithfully round-trip `percent_decode(percent_encode(x)) == x` for any input `x`. However, it should be possible to do that by using the `define_encode_set` macro to define an encode set that contains the `%` character.

**Comment by vi** [comment]
Yes, I implemented my own `EncodeSet` by checking for `b'%'` and proxying everything else to `USERINFO_ENCODE_SET`.

In any case documentation should thoroughtly (in `percent_encode`, in toplevel module, in all pre-defined encodings) mention that `%` is omitted.

Additionally, I think it may be worthy to pre-define percent-inclusive variants of all existing predefined sets.

> It is not designed to faithfully round-trip

Naming of the functions suggest that they should be round-trippable. Maybe documentation should mention when the function is roundtrip-safe and when not.

**Comment by SimonSapin** [comment]
> checking for `b'%'` and proxying everything else

This sounds like you made a manual impl of the trait? The [`define_encode_set`](https://docs.rs/percent-encoding/1.0.1/percent_encoding/macro.define_encode_set.html) macro can do this for you.

**Comment by nox** [comment]
Nothing to do here, closing.

**Comment by vi** [comment]
> Nothing to do here, closing.

Maybe documentation should be more clear about `%` character?
