### ISSUE TITLE
url 1.7.2 and url 2.0.0 disagree whether - is a valid host, intentional?

### ISSUE THREAD

**Issue by jplatte** [servo/rust-url#527]
Some tests in [ruma-identifiers](https://crates.io/crates/ruma-identifiers) that used `-` as an invalid host name broke when upgrade `url` from 1.7.2 to 2.0.0. Is `-` intended to be allowed as a hostname?

**Comment by valenting** [comment]
`new URL("http://-/")` works in both Firefox and Chrome.

**Comment by SimonSapin** [comment]
This sounds related to https://github.com/servo/rust-url/pull/484. @nox, is it possible that he behavior changed even with `check_hyphens: false`?

**Comment by nox** [comment]
AFAIK no, my PR just relaxed some validation errors, it did not add any error case to the best of my knowledge.

**Comment by jplatte** [comment]
Should I try to bisect which commit changed this behaviour maybe?

**Comment by jplatte** [comment]
> did not add any error case

Well url 2.x error in *fewer* cases than 1.x. Maybe it was a bug that this wasn't accepted in 1.x?

**Comment by lucacasonato** [comment]
Let's close as `http://-/` is a valid URL. See https://jsdom.github.io/whatwg-url/#url=aHR0cDovLy0v&base=YWJvdXQ6Ymxhbms=
