### ISSUE TITLE
std::net::ToSocketAddrs dropped from 2.0.0

### ISSUE THREAD

**Issue by saschagrunert** [servo/rust-url#530]
Was it intended to remove the trait `std::net::ToSocketAddrs` from 2.0.0 via https://github.com/servo/rust-url/pull/517 (https://github.com/servo/rust-url/pull/517/commits/6e082014827061a79a27be1d7712e53a84c28280)? I mean these implementation was pretty handy when it comes to create web servers via the `Url` type.

**Comment by SimonSapin** [comment]
Yes it was intended. DNS resolution required a disproportionate amount of API surface, for functionality which is not really what this crate is about.

The replacement looks like this: https://github.com/snapview/tungstenite-rs/pull/63/files#diff-31bbf71c54bca98a0ae3d40a327af940R90

**Comment by saschagrunert** [comment]
I see, thanks for the help :pray:
