### ISSUE TITLE
spec inconsistency wrt forward slash after host if there's no path ?

### ISSUE THREAD

**Issue by o0Ignition0o** [servo/rust-url#531]
As mentioned in my WIP pull request ( #523 ) I'm a bit confused wrt the forward slash uri parsing when there's no path :

[a port setter test](https://github.com/web-platform-tests/wpt/blob/master/url/resources/setters_tests.json#L1362)
 seems to be inconsistent with a [protocol setter test](https://github.com/web-platform-tests/wpt/blob/master/url/resources/setters_tests.json#L230)
There doesn't seem to be any consistency in WPT wrt the "/" when there is no path. 
The [specification](https://url.spec.whatwg.org/#url-serializing) seems to dismiss '/' at the end if there is no path: 
" Otherwise, then for each string in url’s path, append U+002F (/) followed by the string to output."

Does anyone have any pointers on how I'm supposed to handle it ?

**Comment by SimonSapin** [comment]
It’s possible that the spec has changed but the code has not code up yet. See https://github.com/servo/rust-url/issues/163 and https://github.com/servo/rust-url/issues/290.

@nox I think you mentioned something about empty paths? (Without even the initial slash)

**Comment by o0Ignition0o** [comment]
Ok I may want to actually rollback my changes, and apply each patch separately, to make sure I don't get lost in the proces, thank for your reply :)
