### ISSUE TITLE
v2.0 upgrade path

### ISSUE THREAD

**Issue by benesch** [servo/rust-url#532]
First of all, thanks for maintaining this crate! Maintaining an open source project can be thankless work, and especially so when it's a foundational crate like this one.

I recently embarked on upgrading reqwest to url v2.0 (https://github.com/seanmonstar/reqwest/pull/583), and ran into some roadblocks. These roadblocks would have been greatly eased if this crate maintained a changelog or release notes. (If it does, and I've just missed it, apologies! But it's awfully hard to find in that case.) It's very hard to figure out what's changed when upgrading across backwards-incompatible changes without a changelog.

The commit messages don't do a great job of explaining rationale, either. Here's a quick example: https://github.com/servo/rust-url/commit/fe74a60bd0636c5e5da920674b9bbffc22f3c384. Why were the public exports of percent_encoding removed? It's no longer clear to me how to ensure that the version of `percent_encoding` I'm using matches the version used by `url`. I poked at the PR description (https://github.com/servo/rust-url/pull/517), too, and it's no more helpful in explaining the rationale. There's a brief mention of the work item in the 2.0 tracking issue (https://github.com/servo/rust-url/issues/463), but again doesn't present rationale.

The [upgrade guide for 0.1 -> 1.0](https://github.com/servo/rust-url/blob/master/UPGRADING.md), by contrast, is fantastic! I'd like to put one together for 1.0 -> 2.0, but I'll need some help to do so.

Some other issues that could use explaining:

  * percent_encoding no longer exports useful character classes. I had to dig through closed issues to find the rationale for this: https://github.com/servo/rust-url/issues/529;
  * the removal of ToSocketAddr, which is also explained in a closed issue: https://github.com/servo/rust-url/issues/530.

I'd also like to specifically gripe about the removal of `ToSocketAddr`. I've now reimplemented that code poorly—because I wasn't sure how to do it properly—twice [[0]](https://github.com/rushmorem/publicsuffix/commit/40324fa21590d14630a152bbf39dc0e12b3d27a0#diff-b4aea3e418ccdb71239b96952d9cddb6R239) [[1]](https://github.com/seanmonstar/reqwest/pull/583/files#diff-28fb7c5cd7d8c02a6e71edd07ca10d10R334) and @SimonSapin reimplemented it at least once [[0]](https://github.com/snapview/tungstenite-rs/pull/63/files#diff-31bbf71c54bca98a0ae3d40a327af940R94-R109). If we figure out a way to provide `with_default_port` with less API surface, can we bring it back?

**Comment by SimonSapin** [comment]
> how to ensure that the version of `percent_encoding` I'm using matches the version used by `url`

Can you say more about why that’s important? I feel that it’s more important that a future breaking change in `percent_encoding` API would not cause a breaking change in libraries that have a public dependency on `url` but do not use percent encoding functionality.

> `percent_encoding` no longer exports useful character classes

Useful to do what? Were they (in 1.x) really the appropriate ones for your use case?

**Comment by benesch** [comment]
> > how to ensure that the version of `percent_encoding` I'm using matches the version used by `url`
> 
> Can you say more about why that’s important? I feel that it’s more important that a future breaking change in `percent_encoding` API would not cause a breaking change in libraries that have a public dependency on `url` but do not use percent encoding functionality.

Perhaps it's not? I was vaguely worried that something like reqwest could see strange skew because it uses `url` to perform percent encoding in some places, but uses `percent_encoding` in other places.

Most of my concern stemmed from the fact that it seemed like `url` was intentionally exporting `percent_encoding` in 1.0 _because_ it was important that you be able to upgrade your `percent_encoding` and `url` deps in lockstep. I see now that is not actually the case; rather `percent_encoding` was extracted from `url` and the re-export existed for backwards compatibility. (Right?)

Anyway, seems perfectly reasonable to have them decoupled. My concern here is totally solved with the upgrade guide!

> > `percent_encoding` no longer exports useful character classes
> 
> Useful to do what? Were they (in 1.x) really the appropriate ones for your use case?

Well, cookie was using `USERINFO_ENCODE_SET` (https://github.com/SergioBenitez/cookie-rs/pull/122/files#diff-b4aea3e418ccdb71239b96952d9cddb6R84). Full disclosure, though: I haven't checked for sure if that's actually the right thing to do. And reqwest was using `PATH_SEGMENT_ENCODE_SET` (https://github.com/seanmonstar/reqwest/pull/583/files#diff-a3e784467561f56f7fc664d81007a5e0R374-R380) in its multipart implementation.

**Comment by DoumanAsh** [comment]
@SimonSapin In all honestly I believe that you should re-export your dependencies for user to access it so that both would use the same version without need to manually check which version one should use.

**Comment by SimonSapin** [comment]
@benesch I’m hoping this removal will be a nudge to check if that’s the right thing to do.

@DoumanAsh I very much disagree, for the reason given above.
