### ISSUE TITLE
Moving from 1 to 2 version of the crate, how to use percent url encoding?

### ISSUE THREAD

**Issue by vityafx** [servo/rust-url#539]
I have been using this code:

```rust
let encoded_url = utf8_percent_encode(url, QUERY_ENCODE_SET).collect::<String>();
```
But now I don't quite understand what can I do to achieve the same goal. There are no more functions to do this easily as the crate had before.

**Comment by SimonSapin** [comment]
You’re looking for the https://crates.io/crates/percent-encoding crate. Version 1.x of that crate is what was re-exported as `url::percent_encoding` in version 1.x of url.

In version 2.x `QUERY_ENCODE_SET` is gone. Instead you should consider in what the context the encoded string is used, and so which characters need to be encoded. If you’re manipulating the query string component of an URL, the `Url::set_query` method already takes care of percent-encoding so you don’t need to. If you’re manipulating something else, `QUERY_ENCODE_SET` might not be appropriate. https://docs.rs/percent-encoding/2.1.0/percent_encoding/#examples shows how to define a custom set of characters. If you don’t want to bother with that, `NON_ALPHANUMERIC` is the conservative option.

**Comment by vityafx** [comment]
Thank you!
