### ISSUE TITLE
Method to extract origin from a URL

### ISSUE THREAD

**Issue by nkdalmia** [servo/rust-url#54]
Currently, there is no method to extract the origin of a URL as String
* eg: from https://example.com:490/samplefolder/samplefile.txt, extract https://example.com:490/

It would be better if there is a method which does this, otherwise one has to use url.scheme, url.domain() and url.port() to construct the origin.

**Comment by KiChjang** [comment]
I'm not sure whether it's better to use a `struct` or a 3 tuple to encapsulate the result of `origin`, or simply use a string altogether.

**Comment by KiChjang** [comment]
So apparently there is a spec for this: https://url.spec.whatwg.org/#origin
