### ISSUE TITLE
Square brackets should be included in QUERY_ENCODE_SET

### ISSUE THREAD

**Issue by Nashenas88** [servo/rust-url#541]
Per page 18 of [RFC 3986](https://www.ietf.org/rfc/rfc3986.txt):

> A host identified by an Internet Protocol literal address, version 6
   [RFC3513] or later, is distinguished by enclosing the IP literal
   within square brackets ("[" and "]").  This is the only place where
   square bracket characters are allowed in the URI syntax.

Given this, I think they should be included at the lowest level encode set, QUERY_ENCODE_SET. I _think_ SIMPLE_ENCODE_SET could also be used in places where the ip address specification above would be valid, so I wouldn't recommend it there (though I could also be interpreting this incorrectly). 

This would also more closely follow the behavior of Javascript's [encodeURI](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI). Mozilla's documentation also mentions handling of RFC3986:
> Also note that if one wishes to follow the more recent RFC3986 for URLs, which makes square brackets reserved (for IPv6) and thus not encoded when forming something which could be part of a URL (such as a host), the following code snippet may help:
> ```
> function fixedEncodeURI(str) {
>     return encodeURI(str).replace(/%5B/g, '[').replace(/%5D/g, ']');
> }
> ```

So by not encoding square brackets in SIMPLE_ENCODE_SET, hosts could be encoded while leaving the brackets unchanged, while for other parts of the URL, it would be encoded.

**Comment by nox** [comment]
This crate implements the WHATWG URL Living Standard, not the RFCs. The relevant spec for percent-encoding of queries is [this](https://url.spec.whatwg.org/#query-state).

**Comment by Nashenas88** [comment]
Sorry I was not aware of that. I'll close this issue. Thanks for the quick reply!

**Comment by nox** [comment]
Check the result of `new URL("http://foo?bar[blah]=hello")` in the browser of your choice.
