### ISSUE TITLE
Way to convert Host to string

### ISSUE THREAD

**Issue by keirlawson** [servo/rust-url#542]
So far as I can see there is no obvious way, given a `Host`, to serialise it to a string.  Obviously if one has the full `Url` then `host_str()` will do this, but if you only have a `Host` then this is not possible.  Have is missed something, is there a way to do this already?

**Comment by SimonSapin** [comment]
`Host` [implements `Display`](https://docs.rs/url/2.1.0/url/enum.Host.html#impl-Display) and therefore has a `.to_string()` method.

**Comment by djc** [comment]
Looks like this has been answered. Let me know if you have further questions/feedback!
