### ISSUE TITLE
error: local variables in const fn are unstable

### ISSUE THREAD

**Issue by tigerxy** [servo/rust-url#544]
```
:$ cargo run
...
   Compiling percent-encoding v2.1.0
error: local variables in const fn are unstable
  --> /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/percent-encoding-2.1.0/lib.rs:72:13
   |
72 |         let chunk = self.mask[byte as usize / BITS_PER_CHUNK];
   |             ^^^^^

error: aborting due to previous error

error: Could not compile 'percent-encoding'.
```
How can I fix this issue?

**Comment by Eijebong** [comment]
I'd say you need to update to rust 1.33 (at least) https://github.com/servo/rust-url/commit/a1fe49eeaa2fd4c762498e104039884e04740571

**Comment by tigerxy** [comment]
> I'd say you need to update to rust 1.33 (at least) [a1fe49e](https://github.com/servo/rust-url/commit/a1fe49eeaa2fd4c762498e104039884e04740571)

I have version cargo 1.33.0-nightly (2cf1f5dda 2018-12-11)

**Comment by Eijebong** [comment]
That's 1.33 nightly which is older than stable 1.33 and thus doesn't have the same features. If you're using rustup I'd suggest running a `rustup update`.

**Comment by tigerxy** [comment]
> That's 1.33 nightly which is older than stable 1.33 and thus doesn't have the same features. If you're using rustup I'd suggest running a `rustup update`.

Now it is working! Thank you and sorry for asking a noob question.

**Comment by Eijebong** [comment]
No problem, happy to help :)

**Comment by Larusso** [comment]
Noob question from my side about this. Is it normal that crates push minor updates but breaking compatibility with certain rust versions?

**Comment by SimonSapin** [comment]
There is not clear consensus in the Rust ecosystem about whether increasing the minimum compiler version should be considered a breaking change according to SemVer and be reflected in the version number accordingly.

Either way, in this case the `percent-encoding` started relying on `const fn` in version 2.0.0, at the same time as making other breaking API changes.

**Comment by Larusso** [comment]
Ok thanks for the answer. I still have to figure out why my project started to fail even though I pinned the dependencies in the lockfile. 
I specified a rust version to use rather than just the stable channel and a build that worked fine, suddenly failed.
