### ISSUE TITLE
Possibility of query keys without values.

### ISSUE THREAD

**Issue by Argentumbolo** [servo/rust-url#546]
Sometimes API required additional query parameters like:
- https://.../exchange?date=20190915&**json**
- https://.../exchange?date=20190915&**xml**
- https://.../exchange?date=20190915&**bin**
But as I can see `form_urlencoded::Serializer<UrlQuery>` doesn't support it.
In most of cases &**json=1** works just fine, but sometimes no.

Is it possible to add method like `Serializer<UrlQuery>::append_key(&mut self, name: &str)`(without value) in API or it will be against the standards?

**Comment by SimonSapin** [comment]
Regarding the standard, https://url.spec.whatwg.org/#concept-urlencoded-serializer says:

> The application/x-www-form-urlencoded serializer takes a list of name-value tuples tuples

`extend_pairs` implements that. Making it for example skip the `=` when the value is the empty string would be a standard violation.

However adding a separate API sounds fine to me. Maybe with a more explicit name, like `append_key_only` or something.

**Comment by tmccombs** [comment]
It's worth noting that the query string is not necessarily `application/x-www-form-urlencoded` and in this case it sounds like it isn't.

**Comment by Argentumbolo** [comment]
Ok. Anyway I'll try.
I definetely not sure about [form_urlencoded.rs:327](https://github.com/servo/rust-url/pull/547/commits/7e8bdc25c8a04a1d9e2ddc5bd6b0760b153ee67c#diff-dc92ccb68552eb80b22f8eb4dd93f4caR328) because honestly I don't understand what's going on there.

**Comment by jayaddison** [comment]
@Argentumbolo This would be useful for me too (as part of both serializing and deserializing empty query keys as `null`), and I'll see whether your pull request could help.

There was also some discussion in https://github.com/whatwg/url/issues/469 that may be relevant to this thread.

**Comment by djc** [comment]
This was fixed in #547.
