### ISSUE TITLE
`Url::from_file_path` adds an extra leading `/` to paths on Windows

### ISSUE THREAD

**Issue by Mischa-Alff** [servo/rust-url#551]
Commit 9e759f18726c8e1343162922b87163d4dd08fe3c introduces a bug in `Url::from_file_path` on Windows where an extra `/` is inserted before the drive letter, making the URL point to an invalid path. `Url::to_file_path` returns the path with the extra `/`, as it should, so it will make e.g `Path::exists` fail. ( see https://github.com/servo/rust-url/commit/9e759f18726c8e1343162922b87163d4dd08fe3c#diff-b4aea3e418ccdb71239b96952d9cddb6R656 )

It probably worked the commit before, where the code was: 
https://github.com/servo/rust-url/commit/9e759f18726c8e1343162922b87163d4dd08fe3c#diff-b4aea3e418ccdb71239b96952d9cddb6L1093

A simple example is as follows:
```rust
use url::Url;

fn main() {
	let base_path = "D:\\git\\biohazard\\playground\\Cargo.toml";
	println!("base_path: {}", base_path);
	println!("Url::from_file_path(base_path): {}", Url::from_file_path(base_path).unwrap().into_string());

	let canonical_path = std::fs::canonicalize(base_path).unwrap();
	println!("canonical_path: {}", canonical_path.to_str().unwrap());
	println!("Url::from_file_path(canonical_path): {}", Url::from_file_path(canonical_path).unwrap().into_string());
}
```

On my machine, this outputs:
```
base_path: D:\git\biohazard\playground\Cargo.toml
Url::from_file_path(base_path): file:///D:/git/biohazard/playground/Cargo.toml
canonical_path: \\?\D:\git\biohazard\playground\Cargo.toml
Url::from_file_path(canonical_path): file:///D:/git/biohazard/playground/Cargo.toml
```

Instead of `file:///D:/...` those paths should be `file://D:/...`.

A simple fix should be to the line at: https://github.com/servo/rust-url/blob/7d2c9d6ceb3307a3fad4c4bcb7f5b07b5e24c755/src/lib.rs#L2418

I can make a PR with those changes if that solution is accepted.

**Comment by SimonSapin** [comment]
> Instead of `file:///D:/...` those paths should be `file://D:/...`.

Should it really? Because that would represent a URL with path `/...` on the (network / remote) host with name `D:`

**Comment by Mischa-Alff** [comment]
I see what you mean, but rust-url won't properly parse that URL itself, should `Url::to_file_path` be fixed instead?

**Comment by SimonSapin** [comment]
> won't properly parse that URL itself

That sounds like a bug, please provide a test case for that with expected and actual results.

**Comment by Mischa-Alff** [comment]
Okay, I narrowed down the problem further, I'll create a separate issue for it.
