### ISSUE TITLE
Remove gopher from list of special schemes

### ISSUE THREAD

**Issue by CYBAI** [servo/rust-url#556]
whatwg/url#453
web-platform-tests/wpt#19770

**Comment by jamestomasino** [comment]
whatwg is heavily focused on HTML. Their choice to drop support for other protocols is understandable based on those goals. Rust is bigger than just the web, as are URLs, despite their opinion. 

There are gopher clients in the wild relying on this implantation in rust-url. Gopher still exists and had users. Dropping support here will not significantly change the library, but it will have significant impact on those users.

**Comment by SimonSapin** [comment]
Making a scheme "non-special" doesn’t mean you can’t use it, only that some details of [the parsing algorithm](https://url.spec.whatwg.org/#url-parsing) are different.

**Comment by jamestomasino** [comment]
Egg on my face! What would actually change from this, then? Will gopher urls still know that gopher runs on Port 70 by default?

**Comment by tmccombs** [comment]
> Making a scheme "non-special" doesn’t mean you can’t use it, only that some details of the parsing algorithm are different.

Which also changes the behaviour of certain setter methods, since they follow the parsing algorithm. See https://github.com/servo/rust-url/issues/577 and https://github.com/servo/rust-url/issues/579

**Comment by djc** [comment]
This was fixed in 2f204d0037882d742c4f9c6660356967982219d6.

**Comment by tmccombs** [comment]
I wonder if it would make since to have some way for users of rust-url to specify that a scheme is "special". Perhaps a method on `ParseOptions` either to force "specialness", or  give a list of additional schemes to treat as "special"?

**Comment by djc** [comment]
Seems like a decent proposal on the face of it. Let's discuss in #577?
