### ISSUE TITLE
punycode::encode_str() allocates needlessly

### ISSUE THREAD

**Issue by Shnatsel** [servo/rust-url#561]
The following code performs an unnecessary allocation:

https://github.com/servo/rust-url/blob/7d2c9d6ceb3307a3fad4c4bcb7f5b07b5e24c755/idna/src/punycode.rs#L132-L138

Instead of converting `&str` to `Vec<char>` and passing that to `fn encode(input: &[char])`, you can create a private function that accepts `IntoIterator<char>` and serves the use cases of both `encode` and `encode_str` without requiring an extra allocation.

**Comment by SimonSapin** [comment]
I think it may need to be something like `Iterator<char> + ExactSizeIterator + Clone`, given how the slice is currently used. But yeah, that sounds good.
