### ISSUE TITLE
feature: impl TryFrom<&str> for Url

### ISSUE THREAD

**Issue by yoshuawuyts** [servo/rust-url#568]
Having `impl TryFrom<&str> for Url` would be fantastic because it would allow passing both `Url` and `&str` to the same API through an `impl TryInto<Url>` bound.

## Example

```rust
fn make_request(impl TryInto<Url>) -> Result<(), ParseError>;
```

```rust
// Pass a literal directly.
let mut req = make_request("https://example.com")?;

// Create a url, manipulate it, then pass it.
let url = Url::parse("https://example.com")?;
validate_url(&url)?;
let mut req = make_request(url)?;
```

## Caveats

The only caveat here is that `TryFrom` and `TryInto` were stabilized in Rust 1.34, and the minimum guaranteed Rust version for `url` is 1.33, which means this would likely would require a major version bump.

---

Thanks!

**Comment by tmccombs** [comment]
> which means this would likely would require a major version bump

Or add a feature to enable this (and possibly other features that require a more recent version of rust)

**Comment by yoshuawuyts** [comment]
@tmccombs oh brilliant; didn't think of that. Issued #569 with an implementation. Hope it's good!

_edit: Oops, misclicked and accidentally closed this issue._

**Comment by yoshuawuyts** [comment]
Ah since https://github.com/servo/rust-url/issues/566 landed the minimum supported Rust version is now 1.36, which means the flag would no longer serve any purpose.
