### ISSUE TITLE
Parsing username:password is not spec compliant

### ISSUE THREAD

**Issue by segfaultsourcery** [servo/rust-url#580]
Based on this RFC2617 Specification, HTTP Basic Authentication userid can contain any TEXT excluding the symbol ":". The password can contain any TEXT.

https://tools.ietf.org/html/rfc2617#page-6

I had the brilliant idea of setting the username to "https" and the password to "//". This breaks in unexpected ways.

I wrote a few tests to see what effect it actually has, and all tests except `scheme_is_parsed_correctly` fail. Given the way `path_is_parsed_correctly` breaks, I suspect it's because Url doesn't expect there to be any slashes in the password.

```toml
[dependencies]
url = "2.1.1"
```

```rust
use url::Url;
const URL: &str = "http://https://@www.server.com:789/hello";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn scheme_is_parsed_correctly() {
        let result = Url::parse(URL).unwrap();
        assert_eq!(result.scheme(), "http")  // This works as expected.
    }

    #[test]
    fn hostname_is_parsed_correctly() {
        let result = Url::parse(URL).unwrap();
        assert_eq!(result.host_str(), Some("www.server.com")) // Will be "https".
    }

    #[test]
    fn username_is_parsed_correctly() {
        let result = Url::parse(URL).unwrap();
        assert_eq!(result.username(), "https")  // Will be "".
    }

    #[test]
    fn password_is_parsed_correctly() {
        let result = Url::parse(URL).unwrap();
        assert_eq!(result.password(), Some("//"))  // Will be None.
    }

    #[test]
    fn port_is_parsed_correctly() {
        let result = Url::parse(URL).unwrap();
        assert_eq!(result.port(), Some(789))  // Will be None.
    }

    #[test]
    fn path_is_parsed_correctly() {
        let result = Url::parse(URL).unwrap();
        assert_eq!(result.path(), "/hello")  // Will be "//@www.server.com:789/hello".
    }
}
```

**Comment by SimonSapin** [comment]
The spec being implemented is https://url.spec.whatwg.org/#url-parsing

**Comment by segfaultsourcery** [comment]
I see, so the slash should be encoded as %2F, and I should change the URL like this?

```rust
const URL: &str = "http://https:%2F%2F@www.server.com:789/hello";
```

That still gives me the following error:

```text
Expected :Some("//")
Actual   :Some("%2F%2F")
```

Is it not actually up to Url to parse the escaped strings?

**Comment by SimonSapin** [comment]
`Url::parse` does do something called parsing, but the result contains components that are percent-encoded. To unescape you can then use https://docs.rs/percent-encoding/2.1.0/percent_encoding/fn.percent_decode_str.html and https://docs.rs/percent-encoding/2.1.0/percent_encoding/struct.PercentDecode.html#method.decode_utf8

**Comment by segfaultsourcery** [comment]
Okay, thanks for clarifying!
