### ISSUE TITLE
Regression in paths without hosts in v2.1.1 vs v2.1.0

### ISSUE THREAD

**Issue by russelltg** [servo/rust-url#581]
The code
```rust
println!("{:?}", url::Url::parse("udp://:2223"));
```
Prints `Ok("udp://:2223/")` in v2.1.0, but now prints `Err(EmptyHost)` in v2.1.1. Is this an intended change? Is there any way I can get it to parse these hostless urls?

**Comment by djc** [comment]
Yeah, I guess this is intended behavior. It also seems fairly reasonable, so I'll close this issue. Feel free to reopen if you disagree and have a better plan of action!
