### ISSUE TITLE
Parsing git remote URL?

### ISSUE THREAD

**Issue by bradwood** [servo/rust-url#599]
Hi,

I'm trying to parse something like `git@github.com:name/repo.git` -- is this supported? Is it even a valid URL?

I get `RelativeUrlWithoutBase` when I try.

Many thanks

**Comment by tmccombs** [comment]
I think you want to use: `git://git@github.com:name/repo.git`

**Comment by djc** [comment]
Yeah, this doesn't seem to be a valid URL per the URL Standard. In particular, a valid URL must start with a scheme, and the scheme cannot contain `@`. I'm going to close this for now, let me know if you have any further feedback.
