### ISSUE TITLE
Separate form_urlencoded into its own crate

### ISSUE THREAD

**Issue by jplatte** [servo/rust-url#605]
Hi! I'm trying to trim [Ruma](https://github.com/ruma/ruma)'s dependencies, and noticed that the url crate, of which we only use the `form_urlencoded` module (which AFAICT doesn't require any external dependencies) is the only reason for the inclusion of `idna`, `unicode-bidi`, `unicode-normalization` and `smallvec` in our dep graph. Would a PR separating it out into its own crate like `percent-encoding` be considered?

**Comment by valenting** [comment]
Splitting it out would probably be OK, and I think we can do it without breaking the API.

**Comment by jplatte** [comment]
Awesome! Will work on a PR as soon as I find the time.
