### ISSUE TITLE
IP is not recognized in RTSP url

### ISSUE THREAD

**Issue by 0xd34d10cc** [servo/rust-url#606]
I would expect the following assert to pass:
```rust
    assert_eq!(
        Url::parse("http://1.35.33.49").unwrap().host(),
        Url::parse("rtsp://1.35.33.49").unwrap().host()
    )
```
but it [does not](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ab1bcddc46dbcff268cf542b0a1bb424):
```
assertion failed: `(left == right)`
  left: `Some(Ipv4(1.35.33.49))`,
 right: `Some(Domain("1.35.33.49"))`', src/main.rs:4:5
```

**Comment by djc** [comment]
The URL Standard has special handling for several URL schemes (one of which is `http`) that includes parsing the host address to check for IPv4 addresses, but this is not used for unrecognized schemes. Why is the equivalence important to your use case?

**Comment by 0xd34d10cc** [comment]
It's not really _important_ . It's just inconvenient. I have to write code like this:
```rust
match host {
    Host::Domain(name) => {
        if let Ok(ip) = name.parse::<IpAddr>() {
            ip
        } else {
            resolve(name)
        }
    }
    Host::Ipv4(ip) => IpAddr::V4(ip),
    Host::Ipv6(ip) => IpAddr::V6(ip),
}
```
to gen ip address from url. 

I didn't know that this was the intended behavior, it looked like a bug to me. Since that's how the URL Standard requires the parser to work the issue could be closed.

**Comment by tmccombs** [comment]
> The URL Standard has special handling for several URL schemes (one of which is `http`) that includes parsing the host address to check for IPv4 addresses, but this is not used for unrecognized schemes. Why is the equivalence important to your use case?

What is the motivation of that? I can't think of any scheme, except maybe "file", where the host can't be an ip address.

**Comment by djc** [comment]
See here: https://github.com/servo/rust-url/issues/577#issuecomment-678105309.
