### ISSUE TITLE
Fails to compile: Mismatched Types

### ISSUE THREAD

**Issue by caemor** [servo/rust-url#608]
I assume the problem is only at my end since this version is out and well used since 5 months ago.

I tried cargo clean and rebuild everything but it didn't resolve this problem.

```Bash
❯ cargo check
    Checking url v2.1.1
error[E0308]: mismatched types
   --> /home/caemor/.cargo/registry/src/github.com-1ecc6299db9ec823/url-2.1.1/src/lib.rs:298:9
    |
291 |       pub fn parse_with_params<I, K, V>(input: &str, iter: I) -> Result<Url, ::ParseError>
    |                                                                  ------------------------- expected `std::result::Result<Url, parser::ParseError>` because of return type
...
298 | /         Url::options()
299 | |             .parse(input)
300 | |             .map(|url| url.query_pairs_mut().extend_pairs(iter))
    | |________________________________________________________________^ expected struct `Url`, found mutable reference
    |
    = note: expected enum `std::result::Result<Url, _>`
               found enum `std::result::Result<&mut form_urlencoded::Serializer<'_, UrlQuery<'_>>, _>`

error: aborting due to previous error

```

**Comment by hammerandtongs** [comment]
Also ran into this with Url "2.1.1" in my Cargo.toml but got -

"""the trait `tungstenite::client::IntoClientRequest` is not implemented for `url::Url`"""

**Comment by djc** [comment]
The source code you have there does not match the source code as recorded by docs.rs:

https://docs.rs/url/2.1.1/src/url/lib.rs.html#290

or the source code at the v2.1.1 tag in the repository:

https://github.com/servo/rust-url/blob/v2.1.1/src/lib.rs#L290

Maybe you have some `patch` or `replace` going on in your Cargo manifest, either at the crate level or at the workspace level? Might want to inspect your Cargo lockfile. Also, maybe check what compiler version you're using.

(Please let me know if you've resolved this by now.)

**Comment by caemor** [comment]
Thanks, I already got it resolved by removing the url from my local cargo cache and therefore forcing it to reload a correct version.
