### ISSUE TITLE
[Spec Update] Non-special URLs are not idempotent

### ISSUE THREAD

**Issue by CYBAI** [servo/rust-url#628]
Spec: https://github.com/whatwg/url/pull/505
WPT: web-platform-tests/wpt#25113

**Comment by valenting** [comment]
I have a patch that (partly?) fixes this issue in https://github.com/valenting/rust-url/tree/non-special-idempotent
@djc can you take over landing that patch? It hasn't been rebased on the most recent changes.

**Comment by djc** [comment]
I'd prefer to keep this discussion on the original issue, #601. Thanks for filing!

**Comment by CYBAI** [comment]
Oops! Sorry for that I didn't notice the existing one 😂 Thanks for both of your super fast response!
