### ISSUE TITLE
to_file_path on issues on linux

### ISSUE THREAD

**Issue by clegaard** [servo/rust-url#631]
I encountered an issue of file URIs not being converted to filesystem paths correctly by *to_file_path* on Linux. The functionality works as expected on Windows.

Parsing the following URI yields Err(()):
```
file://home/au/Desktop/pyfmu/examples/exported/Adder/resources
```
Using the debugger it seems that it is jumping into the last case of the match statement.

https://github.com/servo/rust-url/blob/3b587ea32f87b40157ad1aa686e5b0bc1b38a5c4/url/src/lib.rs#L2294-L2307

**Comment by tmccombs** [comment]
You need theee slashes between the colon and home

**Comment by djc** [comment]
As the code states, on non-Windows systems the `host` must be empty. This is achieved (as @tmccombs suggests) by using "file:///home/au/Desktop/pyfmu/examples/exported/Adder/resources" rather than the two slashes version.
