### ISSUE TITLE
Parsing file:../../images/vimwiki_logo.png does not fail but does not retain relative path

### ISSUE THREAD

**Issue by chipsenkbeil** [servo/rust-url#641]
```rust
// Succeeds in parsing file URI
let url = Url::parse("file:../../images/vimwiki_logo.png").unwrap();

// Scheme matches
assert_eq!(url.scheme(), "file");

// Fails as the path yielded is "/images/vimwiki_logo.png"
assert_eq!(url.path(), "../../images/vimwiki_logo.png");
```

My expectation would have been to either
a. keep the path as is, but I'm not sure if this is valid file URI syntax as described below
b. return an error that would cause a panic on unwrap

### What is valid file URI syntax?

From what I've read [on the file URI wiki page](https://en.wikipedia.org/wiki/File_URI_scheme), a relative path doesn't sound like a valid format for that URI type. It seems that the file URI requires an absolute path.

I've been trying to see what the current state of the file URI definition is. While there is [rfc3986](https://tools.ietf.org/html/rfc3986#section-3.3) that describes `path-rootless` (allowing relative paths), it seems that `file:` is exempt as described in [rfc8089](https://tools.ietf.org/html/rfc8089#section-2) as requiring an absolute path and/or host.

Or is that not the case? Discussions like [this one](https://stackoverflow.com/questions/7857416/file-uri-scheme-and-relative-files) seem to also imply that you can't do something like `file:../some/path` unless (maybe) it's joined to another `file:` path that is absolute.

**Comment by valenting** [comment]
> My expectation would have been to either
> a. keep the path as is, but I'm not sure if this is valid file URI syntax as described below
> b. return an error that would cause a panic on unwrap

Why would it return an error?

> ### What is valid file URI syntax?
> 
> From what I've read [on the file URI wiki page](https://en.wikipedia.org/wiki/File_URI_scheme), a relative path doesn't sound like a valid format for that URI type. It seems that the file URI requires an absolute path.

This crate implements the [URL Standard](https://url.spec.whatwg.org/).

The example you gave parses the same in Firefox, Chrome and the JS implementation. See here:
https://jsdom.github.io/whatwg-url/#url=ZmlsZTouLi8uLi9pbWFnZXMvdmltd2lraV9sb2dvLnBuZw==&base=YWJvdXQ6Ymxhbms=
