### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by jsha** [servo/rust-url#644]
Hi rust-url folks,

Very much appreciate your work!

Would you be able to cut a new release anytime soon? I'd like to depend on the `TryFrom<&str>` implementation added in https://github.com/servo/rust-url/pull/569. It looks like a couple of other folks have gotten hung up on the fact that this support is implemented but not yet released: #624, #638.

Thanks,
Jacob

**Comment by djc** [comment]
It'd be nice to get #635 merged, and we still have updates to do to match the current standard in #629 and #642.

I could probably push this forward if I had access.

**Comment by valenting** [comment]
I'll try to do a minor release later today.

@djc I'm happy to review your PRs

**Comment by Progdrasil** [comment]
It would be great to have `TryFrom` available for the `Url` type

**Comment by valenting** [comment]
I just published 2.2.0. Sorry for taking so long to do this.

**Comment by Progdrasil** [comment]
Thank you, I'm sure many people will be very happy. And thanks for the great work on this library!
