### ISSUE TITLE
Out of index error found by afl.rs

### ISSUE THREAD

**Issue by StevenJiang1110** [servo/rust-url#656]
I run afl.rs on url2.2.0 with the patch mentioned in #655 ，and I found new out of index error(The error should have nothing about the patch, for it can be replayed on version2.2.0 without patch). The code to replay the error is
```rust
let mut _local0 = url::Url::parse("m://").unwrap();
let mut _local1 = url::Url::path_segments_mut(&mut _local0).unwrap();
let _ = url::PathSegmentsMut::pop_if_empty(&mut _local1);
```
or
```rust
let mut _local0 = url::Url::parse("o://").unwrap();
let mut _local1 = url::Url::path_segments_mut(&mut _local0).unwrap();
let _ = url::PathSegmentsMut::pop(&mut _local1);
```
(I guess this two is about the same error)
I put the replay files and more inputs that may cause crash on
[first](https://github.com/StevenJiang1110/afl_rust_crashes/tree/main/url/replay_url1-13)
[second](https://github.com/StevenJiang1110/afl_rust_crashes/tree/main/url/replay_url2-73)
It seems the url with empty content after "//" or url with some specific unicode characters may lead to the panic.
I hope you will check if this is a real bug. Thanks a lot.

**Comment by StevenJiang1110** [comment]
The total bug report with `RUST_BACKTRACE=full` is like this
![截屏2020-12-04 下午3 01 37](https://user-images.githubusercontent.com/27764680/101132301-bdcc7780-3641-11eb-8a3a-7d6ca593638b.png)

**Comment by djc** [comment]
Thanks for the report, keep 'em coming if there's anything more!
