### ISSUE TITLE
Cargo fuzz finds crash in parse

### ISSUE THREAD

**Issue by eagraf** [servo/rust-url#663]
I ran cargo fuzz on the parse test harness. It exited pretty quickly with a crash on this input: `K:/.//://@K:/.K/://@K:/./!`

**Comment by qsantos** [comment]
I have not been able to reproduce with the code below, even on commits from early 2020. Am I missing something?
```
#[test]
fn test_crash() {
    url::Url::parse("K:/.//://@K:/.K/://@K:/./!").unwrap();
}
```

**Comment by valenting** [comment]
Works for me too.
