### ISSUE TITLE
Serialization of `%7e` in path segment seems to be wrong

### ISSUE THREAD

**Issue by malaire** [servo/rust-url#664]
`Url::parse("http://example.com/%7efoo").unwrap().as_str()` returns `http://example.com/%7efoo`

But URL standard says that path segments are percent-encoded using "path percent-encode set" which doesn't include `~`, so my understanding is that returned value should be `http://example.com/~foo` instead.

**Comment by valenting** [comment]
> But URL standard says that path segments are **percent-encoded** using "path percent-encode set" which doesn't include `~`, so my understanding is that returned value should be `http://example.com/~foo` instead.

My reading of https://url.spec.whatwg.org/#path-state is exactly that.
It doesn't say the path should be percent decoded - instead it's percent encoded meaning parsing http://example.com/`{} turns into http://example.com/%60%7B%7D
Unless I'm misreading something percent decoding isn't necessary.

Server implementations are expected to do percent decoding when turning a URL path into a file path if necessary.

**Comment by malaire** [comment]
So you are saying that URLs `http://example.com/%7efoo` and `http://example.com/~foo` are **not equivalent** according to current URL standard, as equivalence is determined by serialized form of the URL.

These used to be equivalent according to RFC 3986, so this would be quite a change in URL specification.

**Comment by malaire** [comment]
I don't understand how you can claim that e.g. `http://example.com/%66%6f%6f` and `http://example.com/foo` are **not equal**, but just to be sure I opened issues on URL standard: https://github.com/whatwg/url/issues/565

**Comment by Boody6343** [comment]
ABDULLHA
