### ISSUE TITLE
get_query

### ISSUE THREAD

**Issue by 89z** [servo/rust-url#671]
I see the `query_pairs` method [1], and the `set_query` method [2], but I am
not seeing a `get_query` method or similar. For example, given this input:

~~~
month=March&day=Friday
~~~

either as a string or query "object", by providing `month` you could get back
`March`. This is available in other languages, for example Go [3] or Nim [4].

1. https://docs.rs/url/latest/url/struct.Url.html#method.query_pairs
2. https://docs.rs/url/latest/url/struct.Url.html#method.set_query
3. https://golang.org/pkg/net/url#ParseQuery
4. https://nim-lang.github.io/Nim/uri.html#decodeQuery.i,string

**Comment by djc** [comment]
Do you mean [`query()`](https://docs.rs/url/2.2.0/url/struct.Url.html#method.query)? In Rust, the API guidelines recommend against `get_()` prefixes for most simple getters.

**Comment by djc** [comment]
In general, this should do what you're looking for:

```rust
use url::Url;

fn main() {
    let url = Url::parse("https://localhost?page=2&sort=desc").unwrap();
    println!("{:?}", url.query_pairs().find(|(key, _)| key == "page"));
}
```

**Comment by 89z** [comment]
That doesnt really seem in the spirit of a correct answer, as a query string is
essentially a map, not an array. I came up with this instead [1]:

~~~rust
use {
   std::collections::HashMap,
   url::Url
};

fn query(u: Url) -> HashMap<String, String> {
   u.query_pairs().into_owned().collect()
}

fn main() -> Result<(), url::ParseError> {
   let u = Url::parse("http://github.com?month=May&day=Friday")?;
   let q = query(u);
   println!("{:?}", q);
   Ok(())
}
~~~

Also I found this other crate [2] that seems to work as well:

~~~rust
use auris::URI;

fn main() -> Result<(), auris::ParseError> {
   let u: URI<String> = "http://github.com?month=May&day=Friday".parse()?;
   println!("{:?}", u.qs); // Some({"month": "May", "day": "Friday"})
   Ok(())
}
~~~

1. https://stackoverflow.com/questions/43272935
2. https://github.com/bluemoon/auris

**Comment by valenting** [comment]
Except that the query is defined as a string.
You can always have a URL such as `http://example.org/?a=1&a=2&a=3` - in which case what would be the value for `a` - the first or the last instance? Or maybe an array of both?

This way, if you need a map, you can build it yourself, using the rules you choose.
The `query_pairs` method is meant to mirror the [URLSearchParams](https://url.spec.whatwg.org/#interface-urlsearchparams) object.

Hope this helps. Thanks!

**Comment by 89z** [comment]
@valenting

> Except that the query is defined as a string.

No, a query is an object, that can be encoded as a string. A naive
representation of a query object would be:

~~~
type query map[string]string
~~~

> You can always have a URL such as `http://example.org/?a=1&a=2&a=3` - in
> which case what would be the value for `a` - the first or the last instance?
> Or maybe an array of both?

I find it strange that you are talking about this like its an unsolved problem.
Several other languages have dealt with this by revising my above definition to
this:

~~~
type query map[string][]string
~~~

where you have a map of strings, and the value is an array of strings. So given
your example, the object would look like this:

~~~
{"a": ["1", "2", "3"]}
~~~

This is done in Go [1], Python [2], Dart [3], JavaScript [4] and others.

1. https://golang.org/pkg/net/url#Values
2. https://docs.python.org/library/urllib.parse.html
3. https://api.dart.dev/dart-core/Uri-class.html
4. https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams

> This way, if you need a map, you can build it yourself, using the rules you
> choose.

There is no need to have the end user make this kind of decision. Again a query
object is well defined as I linked above, so there should be no reason to have
to leave it up to the user to decide what the object structure would be

> The `query_pairs` method is meant to mirror the
> [URLSearchParams](https://url.spec.whatwg.org/#interface-urlsearchparams)
> object.

Its strange that you link to this object, as `query_pairs` is nothing like it.
Unlike `query_pairs`, `URLSearchParams` is actually robust in that you have the
`get` method [1], `getAll` method [2], `set` method [3] and `append` method [4].
No similar methods exist in the entire `url` crate. If I missed them, please
point them out to me.

1. https://developer.mozilla.org/docs/Web/API/URLSearchParams/get
2. https://developer.mozilla.org/docs/Web/API/URLSearchParams/getAll
3. https://developer.mozilla.org/docs/Web/API/URLSearchParams/set
4. https://developer.mozilla.org/docs/Web/API/URLSearchParams/append
