### ISSUE TITLE
`idna` declares incompatible dependencies

### ISSUE THREAD

**Issue by mrobakowski** [servo/rust-url#679]
https://github.com/servo/rust-url/commit/e579c03677b864d54de5c080f6b44d61736fbd11 introduced this import:
```rust
use unicode_normalization::{is_nfc, UnicodeNormalization};
```
yet the version of `unicode-normalization` `idna` says it uses, `0.1.5`, doesn't have `is_nfc` (which seems to be introduced in the next patch version, `0.1.6`). The version isn't pinned, so cargo takes the newest compatible version and that doesn't matter... _unless_ someone has an old `Cargo.lock` file. Then `idna` doesn't compile.

I was updating an old project of mine and it took me like an hour to figure out I not only need to update the versions in the `Cargo.toml` file, but also remove `Cargo.lock` :sweat_smile:

**Comment by djc** [comment]
Oops! Would you mind submitting a PR?

**Comment by mrobakowski** [comment]
Will do

**Comment by mrobakowski** [comment]
Anything against bumping `unicode-normalization` straight to `0.1.17`, which I believe is the newest version?

**Comment by djc** [comment]
I think it probably can't hurt. :)
