### ISSUE TITLE
Publish fuzz, test, and perhaps benches for the crate

### ISSUE THREAD

**Issue by Manishearth** [servo/rust-url#682]
Currently the `url` crate only publishes its code to crates.io.

A lot of large codebases (firefox, Android, etc) vendor all of their dependencies. Android in particular would like to _test_ its dependencies, since it builds against bionic libc which is typically not in everyone else's CI environment.

It would be nice if `fuzz/`, `tests/`, and maybe `benches/` were included in the published packages so that these codebases can continue to use the crates.io version but still be able to test it.

I've gotten similar requests from people doing packaging for Linux distros on crates I maintain, it's not unheard of to want to test crates.io crates as a part of the packaging process.

**Comment by Manishearth** [comment]
cc @SimonSapin

**Comment by Manishearth** [comment]
Hmm, fuzz can't be included because it's a separate crate.

**Comment by djc** [comment]
FWIW, I've also been on the receiving end of issues/PRs to minimize the amount of stuff published to crates.io in order to reduce download sizes for everyone. The test suites for url and idna are relatively bulky.

**Comment by Manishearth** [comment]
Yeah, I've even made PRs like that in the past myself to crates like regex/unicode-normalization/etc where the testsuite contains large test files. I believe in finding a balance. We've gotten requests on unicode-normalization from package maintainers to include tests, and our compromise was to include all the tests that didn't need a giant data file.

The testsuite here is roughly the size of the source itself, I don't think it's that bulky, and it would be nice if we could include it.

**Comment by djc** [comment]
See https://github.com/servo/rust-url/pull/604

**Comment by Manishearth** [comment]
I don't see a strong enough motive there, whereas there _is_ a decent motive here that keeps cropping up in my experience. This is a really small crate, I get that this may make sense for larger crates, but the test folder is just 200KB ungzipped,

And in gzipped package form (which is what _actually_ gets downloaded), it's even smaller, `rust-url` is 43KB without tests and 64KB with tests. I do not think 20KB is worth it _at all_ here, for the potential benefits of reliable CI for large codebase consumers and package maintainers.

I think the lean crate initiative is nice, but there's a huge difference between cutting out large images (which seems to be its initial motivator) and tests, which are _really_ small on the download size.

**Comment by djc** [comment]
Fair enough.
