### ISSUE TITLE
Replace into_string with an implementation of Into<String>?

### ISSUE THREAD

**Issue by dtantsur** [servo/rust-url#685]
It seems that having `Into<String>` for `Url` is quite natural and can be used in more contexts. Thoughts?

If this idea sounds good, I can work on a PR.

**Comment by dtantsur** [comment]
Similarly, implementing `AsRef<str>` may be worth it.

**Comment by tmccombs** [comment]
`into_string` would need to be kept for backwards compatibility (but could be deprecated).  Also, the correct way to do this would be to `impl From<Url> for String`. But adding that implementation seems reasonable to me.

**Comment by djc** [comment]
Adding `impl From<Url> for String` and deprecating `into_string()` sound good to me.

**Comment by dsherret** [comment]
FWIW, I like the explicit `.into_string()` more because:

1. You can be sure by looking at it that it's not cloning. Sometimes people implement `.into()` on references.
2. It's more discoverable because it loves on the struct.
