### ISSUE TITLE
URL encoding is not always correct when using set_query

### ISSUE THREAD

**Issue by ccampbell** [servo/rust-url#688]
This may be more of a misunderstanding on my end, but I ran into this issue when trying to include a base64 encoded value in a query parameter like so:

```rust
let mut url = "https://example.com/foo".parse::<Url>().unwrap();
url.set_query(Some("comp=block&blockid=n82MNvBNIW9B21er6uceuCW2gWIXB+2BAlLkiNJP1fg="));
```

My expectation was that the `blockid` value would be automatically URL encoded:

```
n82MNvBNIW9B21er6uceuCW2gWIXB%2B2BAlLkiNJP1fg%3D
```

But instead it is not altered. Here is a test case on the rust playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9aa028eeb945c5a138b3803d37e8f519

You can see there that the “🙂” _is_ encoded, but the base64 value is not. I understand that `+` and `=` are valid URL characters so this may just be the expectation here, but thought I would create this ticket anyway. Thanks!

**Comment by tmccombs** [comment]
`set_query` sets the entire query string.  I believe it url encodes the input, but expects that query-specific escaping (for characters like "+", "=", and "&") has already been done. After all, how would it know whether a "=" is intended to be escaped or not. In your case, you would probably want to do something like:

```rust
url.query_pairs_mut()
  .append_pair("comp", "block")
  .append_pair("blockid", "n82MNvBNIW9B21er6uceuCW2gWIXB+2BAlLkiNJP1fg=");
  ```
