### ISSUE TITLE
How to make a URL to "http://localhost/../.."?

### ISSUE THREAD

**Issue by svenstaro** [servo/rust-url#689]
For testing purposes, I'd like to attack my own application using malformed URLs, that are possible to send but are improper in practice. Curl allows you to do:
```
curl --path-as-is localhost/../../
```
which is very useful for this purpose. However, I'm using reqwest which only takes proper URL. I'm not really sure how to best accomplish my use case here. I suppose I'd want a raw URL mode of some sort.

**Comment by djc** [comment]
The url crate is completely unrelated to reqwest's `Url` type (and its `IntoUrl` trait), so I don't think you'll find what you need here.

**Comment by svenstaro** [comment]
Hang on, but reqwest uses this crate in its `into_url.rs` so I'm pretty sure this is the right way to go about that. What am I missing?

**Comment by djc** [comment]
Ah, sorry, you're right.

There is no raw URL mode, so I don't think there's an easy way to achieve what you want. In particular, this crate strives to follow the WHATWG URL Standard, which is all about carefully parsing and rooting out adversarial stuff like `..`. I don't think your request falls within the intended scope of this crate.

**Comment by svenstaro** [comment]
Fair enough.
