### ISSUE TITLE
Empty paths are rendered as `/`

### ISSUE THREAD

**Issue by SirWindfield** [servo/rust-url#690]
I'd expect that the rendered url would not contain the trailing slash again if explicitly set to an empty string. Is this intended behaviour? If yes, how can I work around this? The only solution I have in mind is to render it to a string and just slice the last char of it's a slash.

```rust
use url::Url;

fn main() {
    let mut a = Url::parse("http://example.com/").unwrap();
    assert_eq!(a.path(), "/");
 
    a.set_path("");
    assert_eq!(a.as_str(), "http://example.com"); // fails
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c4aa1fbf4dd5b12da9a61f28f1663faf

**Comment by djc** [comment]
This crate strives to adhere to the WHATWG URL Standard, so you can peruse that for the exact details on how to serialize empty paths. I guess you'll have to work around this.

**Comment by SirWindfield** [comment]
Thanks for clarifying! Maybe at this point it might just be easier to spin off a new library with less strict rules that does not follow the above URL standard.

Just to give another rule that kind of works against me: Changing the protocol from http/https to anything other then ws, file, http(s) or the other well known web protocols fails with an error.

Which is exactly the opposite of what I try to do! Besides that, the library is great and high-quality in regards to following the standard and I do understand that features like the above use-case are just plain out-of-scope!
