### ISSUE TITLE
Debug output doesn't show a difference for foo: and foo://

### ISSUE THREAD

**Issue by glandium** [servo/rust-url#693]
```rust
use url::Url;
fn main() {
  assert_eq!(Url::parse("foo:"), Url::parse("foo://"));
}
```
shows:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Ok(Url { scheme: "foo", username: "", password: None, host: None, port: None, path: "", query: None, fragment: None })`,
 right: `Ok(Url { scheme: "foo", username: "", password: None, host: None, port: None, path: "", query: None, fragment: None })`', src/main.rs:3:3
```
([playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9b021e13ecf147ef4c3cac0552fad984))

There is no visible difference between left and right. Now, imagine the real code being `assert_eq!(my_func(), Url::parse(expected).unwrap());` and seeing this error.

**Comment by glandium** [comment]
Needless to say, the re-serialization with `.as_str()` does differ between the two values.

**Comment by djc** [comment]
Yeah, I think I ran into similar problems before. What do you think we should put into the `Debug` impl instead?

**Comment by glandium** [comment]
Maybe exposing `cannot_be_a_base` would be enough?

**Comment by djc** [comment]
See #699.
