### ISSUE TITLE
'+' in path not being encoded

### ISSUE THREAD

**Issue by anacrolix** [servo/rust-url#695]
Separately to '+' in the query corresponding to a space ' ' (like in https://github.com/servo/rust-url/issues/482), I believe '+' in paths should be encoded to %2B. This does not appear to be the case.

Here's a simple test case:

    #[test]
    fn test_url_encodes_path_plus() {
        let mut url = Url::parse("s3://a").unwrap();
        url.path_segments_mut().unwrap().push("a+b");
        assert_eq!(url.as_str(), "s3://a/a%2Bb");
    }
```
thread 'test_url_encodes_path_plus' panicked at 'assertion failed: `(left == right)`
  left: `"s3://a/a+b"`,
 right: `"s3://a/a%2Bb"`'
```

**Comment by valenting** [comment]
The [path-percent-encode-set](https://url.spec.whatwg.org/#path-percent-encode-set) does not contain the `+` character, so it does not need to be encoded.

**Comment by djc** [comment]
Since we follow the URL Standard, I think the following section is normative:

https://url.spec.whatwg.org/#percent-encoded-bytes

This does not have `+` in the **path percent-encode set**. It is in the **component percent-encode set**, but I'm not completely sure what that is used for.

**Comment by valenting** [comment]
The component percent-encode set is used for 
[form-urlencoded](https://github.com/servo/rust-url/blob/6fd1e87de6ef948a19ee5502711517888f66bb60/form_urlencoded/src/lib.rs#L328-L332) which we seem to be doing correctly.

**Comment by anacrolix** [comment]
Thanks. I read in [RFC 3986: Uniform Resource Identifier (URI): Generic Syntax (2.2)](https://tools.ietf.org/html/rfc3986#section-2.2):

> If data for a URI component would conflict with a reserved
   character's purpose as a delimiter, then the conflicting data must be
   percent-encoded before the URI is formed.

`+` is defined as a reserved character:

      reserved    = gen-delims / sub-delims

      gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"

      sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
                  / "*" / "+" / "," / ";" / "="

Later in [section 3.3](https://tools.ietf.org/html/rfc3986#section-3.3) (where path segments are the parts between `/`):

> Aside from dot-segments in hierarchical paths, a path segment is
   considered opaque by the generic syntax.  URI producing applications
   often use the reserved characters allowed in a segment to delimit
   scheme-specific or dereference-handler-specific subcomponents.  For
   example, the semicolon (";") and equals ("=") reserved characters are
   often used to delimit parameters and parameter values applicable to
   that segment.  The comma (",") reserved character is often used for
   similar purposes.  For example, one URI producer might use a segment
   such as "name;v=1.1" to indicate a reference to version 1.1 of
   "name", whereas another might use a segment such as "name,1.1" to
   indicate the same.  Parameter types may be defined by scheme-specific
   semantics, but in most cases the syntax of a parameter is specific to
   the implementation of the URI's dereferencing algorithm.

I see no mention of whether there are specific delimiters to be expected in http path segments, but segments are defined to be 

    segment       = *pchar
    pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"

And `+` here for my usage is *not* intended to be as a delimiter or reference any subcomponent within its path segment. Then by section 2.2:

> If data for a URI component would conflict with a reserved
   character's purpose as a delimiter, then the conflicting data must be
   percent-encoded before the URI is formed.

The `+` should be percent-encoded to avoid conflicting with any use as a delimiter.

I'm not sure that URI and URL are compatible here. I'm interfacing with S3 object HTTP URLs, which may be encoding keys incorrectly (they're replacing `+` with `%2B`, and my client to it that uses the `url` Rust crate does not). Interestingly their "S3 URI"s do not encoded the `+`.

The more I read about URLs vs. URIs the more I think S3 has it wrong.

Thanks for taking a look!

**Comment by valenting** [comment]
This crate does not implement  RFC 3986 but the [URL Spec](url.spec.whatwg.org/)

**Comment by tmccombs** [comment]
But shouldn't ` url.path_segments_mut().unwrap().push("a+b");` be using the _component_  percent encode set (https://url.spec.whatwg.org/#component-percent-encode-set)?

**Comment by tmccombs** [comment]
Furthermore, https://url.spec.whatwg.org/#interface-urlsearchparams says:

> URLSearchParams objects will percent-encode anything in the application/x-www-form-urlencoded percent-encode set, and will encode U+0020 SPACE as U+002B (+).

and the application/x-www-form-urlencoded percent-encode set includes "+".

**Comment by valenting** [comment]
> But shouldn't ` url.path_segments_mut().unwrap().push("a+b");` be using the _component_ percent encode set (https://url.spec.whatwg.org/#component-percent-encode-set)? Which _does_ include the `+`.

Path setters use the [path percent encode set](https://url.spec.whatwg.org/#path-percent-encode-set) 

If you want the path to be form-urlencoded you have to do that manually:
form_urlencoded::Serializer::new ... append_pair ... finish
Then set the path to the output.

**Comment by tmccombs** [comment]
Oh, I misread that as setting a query parameter.
