### ISSUE TITLE
std::error::Error is not implemented for Errors in data-url crate

### ISSUE THREAD

**Issue by lucacasonato** [servo/rust-url#697]
The `data-url` crate does not implement `std::error::Error` (and thus no human readable formatting) for the following errors in that crate:

- `DecodeError`
- `DataUrlError`
- `MimeParsingError`

Is there any reason for this? If not I would be glad to submit a PR.

**Comment by djc** [comment]
Would be happy to review your PR!

**Comment by lucacasonato** [comment]
There is no trait bound of `Error` or `Display` on `E` of `Decoder` or `DecodeError`, so that error can not be formatted. It would be a breaking change to add this bound (and thus would require a `data-url` 0.2.0. Should I add this trait bound or instead just not display the `E` of `DecodeError::WriteError`?

**Comment by lucacasonato** [comment]
Actually to implement `std::error::Error` on `DecodeError`, `E` needs to implement `Debug`. So `DecodeError` can not implement `std::error::Error` without a minor breaking API change in `data-url`.

**Comment by tmccombs** [comment]
You can do something like:

```
impl<E> std::error::Error for DecodeError<E> where E: Debug {
// ...
}
```

then you can add the implementation without requiring a breaking change.

**Comment by lucacasonato** [comment]
Right, because this is an addition it is technically not a breaking change. Good catch! Will update the PR.

**Comment by filips123** [comment]
It seems that `InvalidBase64` still does not implement `std::error::Error`, even on the latest commit from the repository. This still makes it hard to use `decode_to_vec` with `anyhow`'s `context`, which expects errors to implement `std::error::Error`. Can you also implement this in another PR?
