### ISSUE TITLE
Bad parsing of URL parameters

### ISSUE THREAD

**Issue by tomers** [servo/rust-url#701]
It seems that `url` crate implements the `path` function/attribute in a different manner than that of [Python's URL parse library](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlparse).

In [Rust implementation](https://docs.rs/url/2.2.1/url/struct.Url.html#method.path), `path` includes the `param` section of the path:

Rust code:
```rust
use url::Url;

fn main() {
    assert!(Url::parse("http://example.com/v1?param=value").unwrap().path() == "/v1");
    assert!(Url::parse("http://example.com/v1;param=value").unwrap().path() == "/v1;param=value");
}
```

On the other hand, the [Python implementation](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlparse) separates the `params` section from the `path`, since it models a different general structure of a URL: `scheme://netloc/path;parameters?query#fragment`.

Python code:
```sh
$ python3 -c "from urllib.parse import urlparse; assert urlparse('http://example.com/v1;param=value').path == '/v1'"
```

Relevant section of RFC#3986: https://tools.ietf.org/html/rfc3986.html#section-3.3
My understanding from reading the RFC is that both approaches are correct, since the params is not mandatory, and can be regarded as part of the URL, so I am not sure this is a bug in the Rust implementation. However, it would desired to have a way to parse the path without the params part, and also to be able to parse the params.

**Comment by valenting** [comment]
This crate implements the [URL standard](https://url.spec.whatwg.org/).
The parsing  is  working correctly according to the spec and the [reference implementation](https://jsdom.github.io/whatwg-url/#url=aHR0cDovL2V4YW1wbGUuY29tL3YxO3BhcmFtPXZhbHVl&base=YWJvdXQ6Ymxhbms=)

At the moment there's no functionality to parse the parameters out of the path, but this seems like something that could be implemented in a separate crate.
