### ISSUE TITLE
URL Normalization

### ISSUE THREAD

**Issue by silence-coding** [servo/rust-url#715]
Original URL:  https://github.com/rust-lang////%2E./rust/issues
 Actual URL:  https://github.com/rust-lang///rust/issues
 Expected URL：https://github.com/rust/issues

**Comment by silence-coding** [comment]
Original URL:  https://github.com//rust-lang/%2E./rust/issues
 Actual URL:  https://github.com//rust/issues
 Expected URL：https://github.com/rust/issues

**Comment by silence-coding** [comment]
Thinking about Cyclic Coding：
If the project implemented with url crate is an nginx-like proxy, does bad coding pose a risk of bypassing requests when forwarded to the backend service?

% is encoded as %25
```
    let url_str = "https://github.com/rust-lang/%25E./rust/issues";
    let url = url::form_urlencoded::parse(url_str.as_bytes()).next();
    println!("{:?}", url); // url is "https://github.com/rust-lang/%E./rust/issues"
```

**Comment by valenting** [comment]
Why are you expecting //// to be normalized to / ?
The [reference URL Parser](https://jsdom.github.io/whatwg-url/#url=aHR0cHM6Ly9naXRodWIuY29tL3J1c3QtbGFuZy8vLy8lMkUuL3J1c3QvaXNzdWVz&base=YWJvdXQ6Ymxhbms=) seems to have the same behaviour.

I'm not sure I understand the https://github.com/rust-lang/%25E./rust/issues question

**Comment by silence-coding** [comment]
I expect / / / / to standardize to / because I found that tomcat and nginx process this way.
https://tomcat.apache.org/tomcat-10.0-doc///index.html
https://nginx.org/en///download.html

**Comment by valenting** [comment]
That's up to the webserver I suppose.
Most platform APIs work this way, collapsing empty path segments - but as far as I can tell rust-url behaviour complies with the [URL standard](https://url.spec.whatwg.org/).

**Comment by silence-coding** [comment]
I'm very sorry!

The correct information is as follows:

If I implement a proxy with url crate, when I receive a request like the original https://github.com/rust-lang/%252E./rust/issues
As a proxy, I use the URL crate to obtain the https://github.com/rust-lang/%2E./rust/issues for matching verification. When I transfer the https://github.com/rust-lang/%2E./rust/issues to a later service, the later service decodes the https://github.com/rust-lang/%2E./rust/issues to https://github.com/rust/issues, which may be bypassed.
```
    let url_str = "https://github.com/rust-lang/%252E./rust/issues";
    let url = url::form_urlencoded::parse(url_str.as_bytes()).next();
    println!("{:?}", url); // https://github.com/rust-lang/%2E./rust/issues
```

**Comment by silence-coding** [comment]
You are correct, from the sample provided by the standard, / / to / / are defined.

**Comment by silence-coding** [comment]
@valenting [ reference URL Parser ](https://jsdom.github.io/whatwg-url/#url=aHR0cHM6Ly9naXRodWIuY29tL3J1c3QtbGFuZy8lMjUyRS4vcnVzdC9pc3N1ZXM=&base=YWJvdXQ6Ymxhbms=)
```
    let url_str = "https://github.com/rust-lang/%252E./rust/issues";
    let url = url::form_urlencoded::parse(url_str.as_bytes()).next();
    println!("{:?}", url); // https://github.com/rust-lang/%2E./rust/issues
    
    let url = Url::parse(url_str).unwrap(); 
    println!("{}", url); // https://github.com/rust-lang/%252E./rust/issues

```

**Comment by silence-coding** [comment]
Is url::form_urlencoded::parse used for different purposes than Url::parse?

**Comment by valenting** [comment]
form_urlencoded is mostly used when submitting a HTML encoded form.
Url::parse is for regular URL parsing.
