### ISSUE TITLE
Empty Hash Takes Search Parameters 

### ISSUE THREAD

**Issue by guspower** [servo/rust-url#716]
I'm using `rust-url` to parse urls generated by a 3rd party, upstream system. 
One url pattern I'm seeing ends with a structure like `index.html#/?foo=bar&baz=qux` (note the hash)
I expected `query_pairs` to return the `foo` and `baz` pairs but instead they end up in the hash.

I'm unsure whether this is correct behaviour and could do with some guidance. 

I have created a failing test example:
```
{
    "input": "http://example.org/index.html#/?foo=bar",
    "base": "http://example.org/",
    "href": "http://example.org/index.html#/",
    "origin": "http://example.org",
    "protocol": "http:",
    "username": "",
    "password": "",
    "host": "example.org",
    "hostname": "example.org",
    "port": "",
    "pathname": "/index.html",
    "search": "foo=bar",
    "hash": ""
  },
```
In this instance the `hash` is evaluated to `#/?foo=bar` with `search` being empty.

**Comment by valenting** [comment]
Everything after the `#` character goes into the hash, so the behaviour is correct.
If you want to parse the hash as a key/value pairs you'll have to do that 'manually".
You can probably set the search to hash[2..] on a new URL and extract it from there?
