### ISSUE TITLE
Parsing URLs with hashtag in them

### ISSUE THREAD

**Issue by oren0e** [servo/rust-url#719]
How can a URL such as
`https://some.company.com/#/sessions/9cbf1d7e-efad/tests/9cbf1d7e-efa78`
be parsed?
The output of `.path()` returns `/` and `path_segments` returns an empty vector. When I remove the `/#` everything works as expected.

**Comment by tmccombs** [comment]
You can get the portion after the "#" with the `fragment` method. Note that  that is not part of the path, but a different part of the URL called the fragment .

**Comment by valenting** [comment]
Thank you @tmccombs for answering the question.
Indeed, some websites will put a path after the `#` character and deal with parsing it using specialized libraries.
@oren0e if you want to parse such a URL you can create a new URL, set its path to the portion after the `#` and then use `path_segments` as usual. Note that the fragment and path have a different set of allowed characters, so you might find some of them are percent escaped when doing this.

**Comment by oren0e** [comment]
@valenting Thanks for the answer!
I ended up using `fragment()` but I prefer to do it with the url parsing as you suggested. I've actually tried this before but got `ParseError::RelativeUrlWithoutBase` error (because the part after the `#` is indeed without base). Did I do it wrong?

**Comment by valenting** [comment]
If you are only interested about the path, then you can concatenate it with a host just so the parsing works.
For example `http://example.org + [part after #]`. Then use the path as you please.
