### ISSUE TITLE
Please release a new version of data-url

### ISSUE THREAD

**Issue by BlackDex** [servo/rust-url#725]
Hello there,

I'm using the data-url crate in a project, and currently using the latest commit hash as a patch.
Though not much has changed, but it has been made 2018 compatible and multiple clippy fixes if i see the commits.

Would be nice if can remove the patch and make use of the latest commit without using the commit hash.

Thanks in advance.

**Comment by valenting** [comment]
Done.

https://github.com/servo/rust-url/releases/tag/data_url_v0.1.1
https://crates.io/crates/data-url/0.1.1
