### ISSUE TITLE
[Question] Consider make idna optional?

### ISSUE THREAD

**Issue by shuoli84** [servo/rust-url#727]
Background:
I am developing a rust sdk with strong binary size requirement, after introduce url crate, the binary size increased by around 400kb.
I did a quick hack, delete all code reference to idna (4 to 5 places), and compare the final binary size, confirmed idna is the cause. 

```bash
# before 
-rwxr-xr-x  1 xxxxxx staff  1143856 Nov 16 12:12 ../target/release/deps/parse_url-124867e06fe8f448

# after delete idna code
-rwxr-xr-x  1 xxxxxx  staff  591008 Nov 16 12:16 ../target/release/deps/parse_url-8091d2463bfcb288
```

**Comment by valenting** [comment]
This was brought up in #557

When you say `Consider make idna optional` I think you mean make it opt-out not opt-in, via a feature flag, right?
I defer to @SimonSapin on whether we'd want to do that.

**Comment by shuoli84** [comment]
@valenting yap, opt out, it should included in default features.

**Comment by SimonSapin** [comment]
Yes, IDNA depends on some large-ish tables of Unicode data so I’m not surprised about this effect on code size.

A default Cargo feature seems reasonable. (However I don’t expect to dedicate time to rust-url soon, much more than the occasional comment like this.)

**Comment by valenting** [comment]
I'm happy to review a PR that adds the Cargo feature.

**Comment by shuoli84** [comment]
np, I'm more than happy to make a pr.
