### ISSUE TITLE
URLs with spaces do not correctly error out

### ISSUE THREAD

**Issue by Geometrically** [servo/rust-url#736]
- [X] Note that this crate implements the [URL Standard](https://url.spec.whatwg.org/) not RFC 1738 or RFC 3986

**Describe the bug**
If a URL has spaces, `Url::parse()` still successfully returns a URL, when it should error out. 

Minimum example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a89a8ae8e23d310a8afddb75340f6188

This may be me misunderstanding what the functions purpose is - if it's to accept user "mistakes" or compatibility, that makes sense. However, the examples demonstrate this method to be used as validating URLs, which is my use case. Is there a different function for strictly validating URLs? Am I misunderstanding the purpose of this crate?

**Comment by valenting** [comment]
The behavious is similar to that of the [reference implementation[(https://jsdom.github.io/whatwg-url/#url=aHR0cHM6Ly9mb28uYmFyL2V0YyBhYWE=&base=YWJvdXQ6Ymxhbms=)

Spaces in the path are percent encoded.
See step 2.3 of [Path State](https://url.spec.whatwg.org/#path-state)
> UTF-8 percent-encode c using the path percent-encode set and append the result to buffer.

I see the purpose of all URL parsing libraries as to ensure consistent parsing results across different clients. As such, all programs implementing the URL standard should also be percent encoding spaces in the path.
If you're just trying to check if a URL is "valid" (ie. comes from a parsed URL_ you can always check if parsing it leads to the same result, but that depends on your exact use case.

**Comment by Geometrically** [comment]
Thank you!
