### ISSUE TITLE
The code doesn't compile with master nightly rust: rustc 1.0.0-nightly (44a287e6e 2015-01-08 17:03:40 -0800)

### ISSUE THREAD

**Issue by kstep** [servo/rust-url#74]

**Comment by SimonSapin** [comment]
Upgrading is blocked on https://github.com/rust-lang/rust/pull/20563#issuecomment-69336966

**Comment by kstep** [comment]
As it seems you have found a workaround, this issue should be closed.

**Comment by SimonSapin** [comment]
Right, this was fixed in 47da1ddbbbf42ba20a9f813ade7d83b411bacf02. Sorry I forgot about this issue.
