### ISSUE TITLE
Consider release a new version?

### ISSUE THREAD

**Issue by shuoli84** [servo/rust-url#756]
Thanks for all the hard work!
Seems several months passed since the last release, consider release a new version to crates.io?

**Comment by madsmtm** [comment]
Good idea, I'd like to nominate https://github.com/servo/rust-url/issues/742 as a semi-blocker for that?

**Comment by pehala** [comment]
Any news regarding the new release?

**Comment by valenting** [comment]
I released v2.4.0 earlier today.
