### ISSUE TITLE
Under what circumstances can `percent_decode_str` fail?

### ISSUE THREAD

**Issue by david-perez** [servo/rust-url#758]
As far as I can see, [`percent_decode_str`](https://docs.rs/percent-encoding/latest/percent_encoding/fn.percent_decode_str.html) simply delegates to [`percent_decode`](https://docs.rs/percent-encoding/latest/percent_encoding/fn.percent_decode.html), whose implementation is:

https://github.com/servo/rust-url/blob/48fcbe1c543a8350a74b226c17c1ec06c6e19a68/percent_encoding/src/lib.rs#L346-L350

When calling [`PercentDecode::decode_utf8`](https://docs.rs/percent-encoding/latest/percent_encoding/struct.PercentDecode.html),  to get the decoded result, it seems like the implementation can only return an error if the bytes are not valid UTF-8:

https://github.com/servo/rust-url/blob/48fcbe1c543a8350a74b226c17c1ec06c6e19a68/percent_encoding/src/lib.rs#L418-L429

This makes sense when your input is a bytes slice, but for `percent_decode_str`, the input is a `&str`, which is already valid UTF-8. So I can't really see how `percent_decode_str` can fail.

**Comment by Uristqwerty** [comment]
Consider what happens if the input contains a lone %f0. Converting to `Cow` appears to pass though `PercentDecode::if_any`, which in turn *can* produce invalid sequences as it decodes percent-encoded bytes.

**Comment by david-perez** [comment]
@Uristqwerty That makes perfect sense, I had misunderstood the code. Thank you!
