### ISSUE TITLE
Url::parse regression

### ISSUE THREAD

**Issue by kellytk** [servo/rust-url#798]
`let url = url::Url::parse("https://foo.bar.0")?;` has a valid URL and was accepted until recently.

Now it generates the error "invalid IPv4 address".

**Comment by valenting** [comment]
According to the reference URL parser that is an invalid URL:

https://jsdom.github.io/whatwg-url/#url=aHR0cHM6Ly9mb28uYmFyLjA=&base=YWJvdXQ6Ymxhbms=

The recent release implemented https://github.com/whatwg/url/pull/619 which forbids URLs that end in a number.
