### ISSUE TITLE
Please could you export `SchemeType` or add `is_special()` method to `Url`

### ISSUE THREAD

**Issue by samuelcolvin** [servo/rust-url#800]
Currently there's no way to check if a url/scheme is "special" without duplicating logic from 

https://github.com/servo/rust-url/blob/1c1e406874b3d2aa6f36c5d2f3a5c2ea74af9efb/url/src/parser.rs#L161-L167

Would be great if this could be made public, or an `is_special` method added to `Url`.

Also, I guess `SchemeType::from` should probably be implemented via the `Into` trait?

**Comment by qsantos** [comment]
See https://github.com/servo/rust-url/pull/826
