### ISSUE TITLE
non-special domain is never an `Ipv4`

### ISSUE THREAD

**Issue by samuelcolvin** [servo/rust-url#803]
The following code fails on the final assert:

```rs
use url::{Url, Host};

fn main () {
  let u = Url::parse("http://[::1]").unwrap();
  assert_eq!(u.host(), Some(Host::Ipv6("::1".parse().unwrap())));
  
  let u = Url::parse("http://127.0.0.1").unwrap();
  assert_eq!(u.host(), Some(Host::Ipv4("127.0.0.1".parse().unwrap())));
  
  let u = Url::parse("foo://[::1]").unwrap();
  assert_eq!(u.host(), Some(Host::Ipv6("::1".parse().unwrap())));
  
  let u = Url::parse("foo://127.0.0.1").unwrap();
  assert_eq!(u.host(), Some(Host::Ipv4("127.0.0.1".parse().unwrap())));
}
```

With:

```
  left: `Some(Domain("127.0.0.1"))`,
 right: `Some(Ipv4(127.0.0.1))`', src/main.rs:14:3
```

I think this is a bug, I think the behaviour should be the same as for a v6 ip address.

**Comment by valenting** [comment]
According to the [URL standard](https://url.spec.whatwg.org/#host-parsing) non-special URLs are parsed using the opaque host parser. That means the host is just a string, not an IPv4 address.

To exemplify, see parsing [foo](https://jsdom.github.io/whatwg-url/#url=Zm9vOi8vMTI5LjE2OC4xLjk5OQ==&base=YWJvdXQ6Ymxhbms=) vs [http](https://jsdom.github.io/whatwg-url/#url=aHR0cDovLzEyOS4xNjguMS45OTk=&base=YWJvdXQ6Ymxhbms=). http:// rejects an invalid IPv4, whereas foo:// does not.

**Comment by samuelcolvin** [comment]
Interesting, thanks for clarifying.

Sorry for the noise.
