### ISSUE TITLE
percent ("%) character must be percent-encoded as "%25"

### ISSUE THREAD

**Issue by santhosh-tekuri** [servo/rust-url#822]
- [x] Note that this crate implements the [URL Standard](https://url.spec.whatwg.org/) not RFC 1738 or RFC 3986

**Describe the bug**
A clear and concise description of what the bug is. Include code snippets if possible.
From https://www.rfc-editor.org/rfc/rfc3986#section-2.4:

```
Because the percent ("%") character serves as the indicator for
percent-encoded octets, it must be percent-encoded as "%25" for that
octet to be used as data within a URI.
```

below is test case to produce bug:

```rust
let mut url = Url::parse("http://example.com/test").unwrap();
url.set_fragment(Some("ab cd%ef"));
assert_eq!(url.as_str(), "http://example.com/test#ab%20cd%25ef");
```

output:
```
thread 'util::tests::test_equals' panicked at 'assertion failed: `(left == right)`
  left: `"http://example.com/test#ab%20cd%ef"`,
 right: `"http://example.com/test#ab%20cd%25ef"`', src/util.rs:305:9
```

**Comment by valenting** [comment]
> * [x]  Note that this crate implements the [URL Standard](https://url.spec.whatwg.org/) not RFC 1738 or RFC 3986
> 
> **Describe the bug** A clear and concise description of what the bug is. Include code snippets if possible. From https://www.rfc-editor.org/rfc/rfc3986#section-2.4:

I am a bit confused why you checked the box if you're referencing the RFC it explicitly says it doesn't implement. 🙂
Anyways, here's this [test case](https://jsdom.github.io/whatwg-url/#url=aHR0cDovL2V4YW1wbGUuY29tL3Rlc3QjYWIgY2QlZWY=&base=YWJvdXQ6Ymxhbms=) in the reference URL parser
