### ISSUE TITLE
Please add an option to not remove wellknown default ports from URL

### ISSUE THREAD

**Issue by Revolution1** [servo/rust-url#834]
- [x] Note that this crate implements the [URL Standard](https://url.spec.whatwg.org/) not RFC 1738 or RFC 3986

**Describe the bug**
Just like the issue title said, if I feed a string into the parser, at least I can find a method to allow me serialize or just get back the exact string I feed in.

**Comment by valenting** [comment]
We've received a request like this before [#706](https://github.com/servo/rust-url/issues/706#issuecomment-828206974)
My best suggestion is to have a wrapper for the URL that also holds the input you give it.
