### ISSUE TITLE
Integer overflow when parsing long URL

### ISSUE THREAD

**Issue by Byron** [servo/rust-url#870]
When parsing the attached URL ([long.url.zip](https://github.com/servo/rust-url/files/12909032/long.url.zip)) with `url::Url::parse()` when compiled with overflow checks, there will be an overflow in `idna` with the panic.

```
thread '<unnamed>' panicked at /rust/registry/src/index.crates.io-6f17d22bba15001f/idna-0.4.0/src/punycode.rs:272:17:
attempt to add with overflow
```

Without overflow checks, the same will cause an `IdnaError` to be created, but won't panic.

Since the URL is very long, I suppose that this issue can be prevented by avoiding to parse unrealistically long host and domain names, which makes this issue related to #868 .

**Comment by Byron** [comment]
I have another URL of this kind, along with a reproducer directly in [the Rust playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1481a041499cbad4cd541c4a755d206a).

**Comment by Byron** [comment]
Here is another [Rust playground example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=52b98cabd5435407e3009f7e38c59fed) of the same overflow, but using a smaller URL.

**Comment by Byron** [comment]
And another new test-case, which fails in the same spot.

[clusterfuzz-testcase-minimized-gix-url-parse-5849655294164992.zip](https://github.com/servo/rust-url/files/13243590/clusterfuzz-testcase-minimized-gix-url-parse-5849655294164992.zip)

It's sad that the fuzzer keeps creating new cases for the same issue, and I will stop reporting these here now.

**Comment by valenting** [comment]
Fixed by https://github.com/servo/rust-url/pull/877
