### ISSUE TITLE
idna::punycode::encode_str() wrong conversion ?

### ISSUE THREAD

**Issue by dandyvica** [servo/rust-url#884]
- [ ] Note that this crate implements the [URL Standard](https://url.spec.whatwg.org/) not RFC 1738 or RFC 3986

**Describe the bug**
```encode_str("ουτοπία.δπθ.gr")``` gives ```..gr-pldmw6azdale9bn```

Online decoders give ```xn--kxae4bafwg.xn--pxaix.gr```

What's wrong?

**Comment by valenting** [comment]
encode_str should only be used for a single label.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=de549ac54f91648849021b2e0dfc0b6f
```rust
use idna; // 0.4.0
fn main() {
    let x = idna::domain_to_ascii("ουτοπία.δπθ.gr");
    println!("{:?}", x);
    
    let x = idna::punycode::encode_str("ουτοπία.δπθ.gr");
    println!("{:?}", x);
    
    let x = idna::punycode::encode_str("ουτοπία");
    println!("{:?}", x);
}
```

Output:
```
Ok("xn--kxae4bafwg.xn--pxaix.gr")
Some("..gr-pldmw6azdale9bn")
Some("kxae4bafwg")
```

I suppose we could make encode_into return an Err if the input contains any dots [here](https://github.com/servo/rust-url/blob/464b1f7d8fe9de117af184c1acb52b4f821a0cdc/idna/src/punycode.rs#L247), but that shouldn't really be necessary if you use idna::domain_to_ascii instead.

**Comment by dandyvica** [comment]
@valenting Thanks a lot for the explanation !
