### ISSUE TITLE
JOIN functionality not working

### ISSUE THREAD

**Issue by Norlock** [servo/rust-url#896]
- [x] Note that this crate implements the [URL Standard](https://url.spec.whatwg.org/) not RFC 1738 or RFC 3986

**Describe the bug**
The join functionality doesn't work correctly. 

```rust
fn main() {
    let url = url::Url::parse("http://192.0.0.0:3030/unicore/").unwrap();

    let b = url.join("/auth/token/");

    println!("{:?}", b);
}
```

It removed the path /unicore/ instead of joining it. 

Version: latest (2.5).

**Comment by valenting** [comment]
The description of https://docs.rs/url/latest/url/struct.Url.html#method.join says:
> Parse a string as an URL, with this URL as the base URL.

That means it doesn't actually "join the path" but parses the string with the given URL as a base.

What you want is:
```
fn main() {
    let url = url::Url::parse("http://192.0.0.0:3030/unicore/").unwrap();

    let b = url.join("auth/token/"); // Note no leading /

    println!("{:?}", b);
}
```

**Comment by Norlock** [comment]
Can't you add maybe two functions to prevent developers from shooting themselves in the foot? Its very easy to create bugs especially if you add from functions or from environment variables from users, maybe something like:

```rust
pub trait JoinFunctions {
    fn join_path(&mut self, path: &str);
    fn join_file(&mut self, file: &str);
}

impl JoinFunctions for url::Url {
    fn join_path(&mut self, path: &str) {
        let mut path = path.to_string();

        if path.starts_with("/") {
            path.remove(0);
        }

        if !path.ends_with("/") {
            path.push('/')
        }

        self.join(&path);
    }

    fn join_file(&self, file: &str) {
        let mut path = file.to_string();

        if path.starts_with("/") {
            path.remove(0);
        }

        self.join(&path);
    }
}
```

**Comment by valenting** [comment]
If you need full control of the path changing I suggest using `url.path_segments_mut()` instead.
https://docs.rs/url/latest/url/struct.PathSegmentsMut.html

**Comment by valenting** [comment]
I think in the next major revision of the URL crate we might remove join entirely, and add a new Url::parse_with_base(input, base) that works exactly like its DOM equivalent.
