### ISSUE TITLE
`=` is not being escaped correctly in query string

### ISSUE THREAD

**Issue by da-kami** [servo/rust-url#907]
This is related to https://github.com/servo/rust-url/issues/688 but I could pin the problem to `=` in the query string.

I would have expected that the parsed URL would be escaped, but it is not:

```rust
#[test]
    fn query_string_encode() {
        let url = Url::parse("https://www.example.com?q=asdf=").unwrap();
        let query = url.query().unwrap().to_string();
        assert_eq!(query, "q=asdf%3D");
    }
```

```
assertion `left == right` failed
  left: "q=asdf="
 right: "q=asdf%3D"
```

This is a problem specifically for `=` in a query string - other characters are escaped correctly.

e.g. this test passes:

```rust
    #[test]
    fn query_string_encode() {
        let url = Url::parse("https://www.example.com?q=asdf中文字").unwrap();
        let query = url.query().unwrap().to_string();
        assert_eq!(query, "q=asdf%E4%B8%AD%E6%96%87%E5%AD%97");
    }
```

**Comment by valenting** [comment]
> This is related to #688 but I could pin the problem to `=` in the query string.
> I would have expected that the parsed URL would be escaped, but it is not:
>         let url = Url::parse("https://www.example.com?q=asdf=").unwrap();

There are two `=` characters in your input. Why would one be escaped while the other one isn't?
The [URL query percent encode set](https://url.spec.whatwg.org/#query-percent-encode-set) does not contain the `=` character, so it's not escaped.
This is consistent with the [reference URL parser](https://jsdom.github.io/whatwg-url/#url=aHR0cHM6Ly93d3cuZXhhbXBsZS5jb20/cT1hc2RmPQ==&base=YWJvdXQ6Ymxhbms=) and browser implementations.

**Comment by da-kami** [comment]
I would have expected it to be escaped because it is part of the value, not the key part of this query parameter.
The delimiter for multiple query params is typically `&`, and I would have attributed anything between the first `=` and the next delimiter (be it `&`, `/` or the end of the string) to the value.

But as you pointed out the accepted convention doesn't escape `=` in this context. It appears that squid proxy does escape it, so I assumed it would make sense give that it is a common proxy out there. I stand corrected :)
Thanks for adding the references!
