### ISSUE TITLE
No hostname format validation in URL

### ISSUE THREAD

**Issue by mardiros** [servo/rust-url#913]
- [ ] Note that this crate implements the [URL Standard](https://url.spec.whatwg.org/) not RFC 1738 or RFC 3986

**Describe the bug**
A clear and concise description of what the bug is. Include code snippets if possible.

This simple rust program should crash because `-x` is not a valid hostname. (a hostname cannot starts with a `-`)

```
use url::{Host, Url};
fn main() {
    let url = Url::parse("https://-x").unwrap();  // should failed
    assert!(url.host() == Some(Host::Domain("-x")));
}
```

I can't says that it is part of the URL Standard - https://url.spec.whatwg.org/#host-parsing

Following recommandation from pydantic team - https://github.com/pydantic/pydantic/issues/9000

**Comment by valenting** [comment]
According to the URL standard it is.
See the [reference URL parser](https://jsdom.github.io/whatwg-url/#url=aHR0cHM6Ly8teC8=&base=YWJvdXQ6Ymxhbms=)

**Comment by mardiros** [comment]
Hi @valenting 

Thanks for answering.
Sorry to insist, but I don't get it.

Do you mean that the URL standard accept any string as a hostname ? Because DNS server don't.

**Comment by valenting** [comment]
The URL standard accepts lots of things in the hostname that DNS doesn't - such as `https://"'!$&*().com/`
If you disagree, you can argue your case in https://github.com/whatwg/url/issues/new/choose
The implementation in this crate is only going to follow the parsing rules as stated in the URL standard

**Comment by mardiros** [comment]
That is what I've done yesterday - https://github.com/jsdom/whatwg-url/issues/271

They said that this is an url parser, not an URL validator. 

I can't tell that rust-url is a validator or a parser.

**Comment by valenting** [comment]
I don't think we have any intention of implementing domain name validation in the url crate.
That can be an additional check implemented separately from the parsing step.
