### ISSUE TITLE
Possible regression in idna 1.0 with error display output

### ISSUE THREAD

**Issue by jszwedko** [servo/rust-url#961]
**Describe the bug**

Hi all!

I might be missing the new way to get at these, or maybe the change is intentional, but it seems like `idna::Errors` no longer includes specifics about the errors that were hit during parsing that were previously printed when rendering the error.

Example reproduction:

```rust
fn main() {
    let s = "xn--8hbb.xn--fiba.xn--8hbf.xn--eib.";
    let (_, result) = idna::domain_to_unicode(&s);
    // with 0.5.0:
    // [src/main.rs:7:5] result.unwrap_err() = Errors { check_bidi }
    // with 1.0.2:
    // [src/main.rs:4:5] result.unwrap_err() = Errors
    dbg!(result.unwrap_err());
}
```

Is this loss of information intentional?

Is there a list of changes in idna 1.0.0 anywhere? I couldn't find a changelog or release notes.

Thank you!

**Comment by jszwedko** [comment]
I found some notes about breaking changes after 0.5.0 on crates.io: https://crates.io/crates/idna. It doesn't seem to cover mention the behavior I'm running into though.

**Comment by jszwedko** [comment]
Bump on this. Am I missing anything?

**Comment by hsivonen** [comment]
This is intentional. In particular, normalization and mapping is fused in a way where there's no channel to communicate the precise error category. However, you can now run with a config that marks each error with the REPLACEMENT CHARACTER. This allows visualizing where the errors are without characterizign them.

**Comment by jszwedko** [comment]
Thanks for the reply @hsivonen ! I'll close this out since it doesn't seem like the crate will be re-adding this functionality.
