### ISSUE TITLE
License relationship is ambiguous. Definition should mention "OR" or "AND" relation between the two licenses

### ISSUE THREAD

**Issue by guellaeq** [servo/rust-url#981]
**Describe the bug**
The license definition is unclear. There should be some explanations added either in the Cargo.toml or in the README.md file to describe the license relationship. 
Currently, it is impossible to know if this package is licensed with an "AND" or an "OR" between the two licenses

example in the Cargo.toml file from the rust docs : https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields 
```toml
license = "MIT OR Apache-2.0"
```

**Comment by Manishearth** [comment]
The Cargo.toml does have ORs.  

I'd accept a PR to the readme that mentions this repo is dual licensed.
