### ISSUE TITLE
Feature Request: Semicolon params delimiter

### ISSUE THREAD

**Issue by freeform-andre** [servo/rust-url#997]
Hello, Would it be sensible or possible to support producing URLs which use semicolon `;` in place of ampersand `&` when serializing URLs? Or if that's already possible, how might one do that?

Thanks!

**Comment by Manishearth** [comment]
I don't think this is there in the spec, so no. This crate follows the URL WhatWG spec

**Comment by freeform-andre** [comment]
Ah, I hadn't read https://url.spec.whatwg.org/ Thanks for the info and quick response!
