### ISSUE TITLE
`has_punycode_prefix` optimization

### ISSUE THREAD

**Issue by owenthewizard** [servo/rust-url#998]
- [x] Note that this crate implements the [URL Standard](https://url.spec.whatwg.org/) not RFC 1738 or RFC 3986

I'm not very experienced with assembly, so this may be entirely incorrect...

**Describe the bug**
[It seems that the masking performed for `has_punycode_prefix` is slower than simply using `str.starts_with("xn--")`](https://rust.godbolt.org/z/MYo1snqzn). Am I missing something?

**Comment by hsivonen** [comment]
Your code checks only for "xn--". The crate checks for "xn--", "XN--", "Xn--", and "xN--" in one operation.

**Comment by owenthewizard** [comment]
Thank you!
